import type { QueryInterface } from '../runner.js'

export async function up(query: QueryInterface): Promise<void> {
  await query.execute(
    `CREATE TABLE IF NOT EXISTS "mojang" (
      "uuid" TEXT PRIMARY KEY,
      "username" TEXT NOT NULL,
      "loweredName" TEXT NOT NULL,
      "createdAt" INTEGER NOT NULL DEFAULT CAST(EXTRACT(EPOCH FROM NOW()) AS INTEGER)
    )`
  )
  await query.execute(`CREATE UNIQUE INDEX IF NOT EXISTS "mojangLoweredNameUnique" ON "mojang" ("loweredName")`)

  await query.execute(
    `CREATE TABLE IF NOT EXISTS "links" (
      "uuid" TEXT PRIMARY KEY,
      "discordId" TEXT NOT NULL UNIQUE,
      "createdAt" INTEGER NOT NULL DEFAULT CAST(EXTRACT(EPOCH FROM NOW()) AS INTEGER)
    )`
  )

  await query.execute(
    `CREATE TABLE IF NOT EXISTS "DiscordMessages" (
      "timestamp" INTEGER NOT NULL,
      "user" TEXT NOT NULL,
      "count" INTEGER NOT NULL DEFAULT 0,
      PRIMARY KEY ("timestamp", "user")
    )`
  )
  await query.execute(
    `CREATE TABLE IF NOT EXISTS "MinecraftMessages" (
      "timestamp" INTEGER NOT NULL,
      "user" TEXT NOT NULL,
      "count" INTEGER NOT NULL DEFAULT 0,
      PRIMARY KEY ("timestamp", "user")
    )`
  )
  await query.execute(
    `CREATE TABLE IF NOT EXISTS "DiscordCommands" (
      "timestamp" INTEGER NOT NULL,
      "user" TEXT NOT NULL,
      "count" INTEGER NOT NULL DEFAULT 0,
      PRIMARY KEY ("timestamp", "user")
    )`
  )
  await query.execute(
    `CREATE TABLE IF NOT EXISTS "MinecraftCommands" (
      "timestamp" INTEGER NOT NULL,
      "user" TEXT NOT NULL,
      "count" INTEGER NOT NULL DEFAULT 0,
      PRIMARY KEY ("timestamp", "user")
    )`
  )

  await query.execute(
    `CREATE TABLE IF NOT EXISTS "AllMembers" (
      "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      "uuid" TEXT NOT NULL,
      "fromTimestamp" INTEGER NOT NULL,
      "toTimestamp" INTEGER NOT NULL,
      CHECK ("fromTimestamp" <= "toTimestamp")
    )`
  )
  await query.execute(
    `CREATE TABLE IF NOT EXISTS "OnlineMembers" (
      "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      "uuid" TEXT NOT NULL,
      "fromTimestamp" INTEGER NOT NULL,
      "toTimestamp" INTEGER NOT NULL,
      CHECK ("fromTimestamp" <= "toTimestamp")
    )`
  )
  await query.execute(
    `CREATE INDEX IF NOT EXISTS "allMembersUuidIndex" ON "AllMembers" ("uuid", "fromTimestamp", "toTimestamp")`
  )
  await query.execute(
    `CREATE INDEX IF NOT EXISTS "onlineMembersUuidIndex" ON "OnlineMembers" ("uuid", "fromTimestamp", "toTimestamp")`
  )

  await query.execute(
    `CREATE TABLE IF NOT EXISTS "guildMemberStates" (
      "instanceName" TEXT NOT NULL,
      "memberUuid" TEXT NOT NULL,
      "memberName" TEXT NOT NULL,
      "rank" TEXT NOT NULL,
      "joinedAt" INTEGER NOT NULL,
      "lastSeenAt" INTEGER NOT NULL,
      "weeklyGexp" INTEGER NOT NULL,
      "dailyGexp" INTEGER NOT NULL,
      "online" INTEGER NOT NULL,
      "updatedAt" INTEGER NOT NULL DEFAULT CAST(EXTRACT(EPOCH FROM NOW()) AS INTEGER),
      PRIMARY KEY ("instanceName", "memberUuid")
    )`
  )
  await query.execute(
    `CREATE INDEX IF NOT EXISTS "guildMemberStatesInstanceNameIndex" ON "guildMemberStates" ("instanceName")`
  )
  await query.execute(
    `CREATE INDEX IF NOT EXISTS "guildMemberStatesLastSeenIndex" ON "guildMemberStates" ("lastSeenAt")`
  )

  await query.execute(
    `CREATE TABLE IF NOT EXISTS "guildMemberEvents" (
      "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      "instanceName" TEXT NOT NULL,
      "memberUuid" TEXT NOT NULL,
      "memberName" TEXT NOT NULL,
      "eventType" TEXT NOT NULL,
      "rank" TEXT NOT NULL,
      "weeklyGexp" INTEGER NOT NULL,
      "dailyGexp" INTEGER NOT NULL,
      "online" INTEGER NOT NULL,
      "createdAt" INTEGER NOT NULL DEFAULT CAST(EXTRACT(EPOCH FROM NOW()) AS INTEGER)
    )`
  )
  await query.execute(
    `CREATE INDEX IF NOT EXISTS "guildMemberEventsInstanceNameIndex" ON "guildMemberEvents" ("instanceName", "createdAt")`
  )
  await query.execute(
    `CREATE INDEX IF NOT EXISTS "guildMemberEventsMemberUuidIndex" ON "guildMemberEvents" ("memberUuid", "createdAt")`
  )

  await query.execute(
    `CREATE TABLE IF NOT EXISTS "guildMemberDailySnapshots" (
      "snapshotDay" INTEGER NOT NULL,
      "instanceName" TEXT NOT NULL,
      "memberUuid" TEXT NOT NULL,
      "memberName" TEXT NOT NULL,
      "joinedAt" INTEGER NOT NULL,
      "lastSeenAt" INTEGER NOT NULL,
      "weeklyGexp" INTEGER NOT NULL,
      "dailyGexp" INTEGER NOT NULL,
      "online" INTEGER NOT NULL,
      PRIMARY KEY ("snapshotDay", "instanceName", "memberUuid")
    )`
  )
  await query.execute(
    `CREATE INDEX IF NOT EXISTS "guildMemberDailySnapshotsInstanceNameIndex" ON "guildMemberDailySnapshots" ("instanceName", "snapshotDay")`
  )

  await query.execute(
    `CREATE TABLE IF NOT EXISTS "punishments" (
      "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      "originInstance" TEXT NOT NULL,
      "userId" TEXT NOT NULL,
      "type" TEXT NOT NULL,
      "purpose" TEXT NOT NULL,
      "reason" TEXT NOT NULL,
      "createdAt" INTEGER NOT NULL,
      "till" INTEGER NOT NULL
    )`
  )
  await query.execute(`CREATE INDEX IF NOT EXISTS "punishmentsIndex" ON "punishments" ("originInstance", "userId")`)

  await query.execute(
    `CREATE TABLE IF NOT EXISTS "heatsCommands" (
      "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      "originInstance" TEXT NOT NULL,
      "userId" TEXT NOT NULL,
      "type" TEXT NOT NULL,
      "createdAt" INTEGER NOT NULL
    )`
  )
  await query.execute(
    `CREATE TABLE IF NOT EXISTS "heatsCommandsWarnings" (
      "originInstance" TEXT NOT NULL,
      "userId" TEXT NOT NULL,
      "type" TEXT NOT NULL,
      "warnedAt" INTEGER NOT NULL,
      PRIMARY KEY ("originInstance", "userId", "type")
    )`
  )
  await query.execute(`CREATE INDEX IF NOT EXISTS "heatsCommandsIndex" ON "heatsCommands" ("originInstance", "userId")`)

  await query.execute(
    `CREATE TABLE IF NOT EXISTS "autocompleteUsernames" (
      "loweredContent" TEXT PRIMARY KEY,
      "content" TEXT NOT NULL,
      "timestamp" INTEGER NOT NULL
    )`
  )
  await query.execute(
    `CREATE TABLE IF NOT EXISTS "autocompleteRanks" (
      "loweredContent" TEXT PRIMARY KEY,
      "content" TEXT NOT NULL,
      "timestamp" INTEGER NOT NULL
    )`
  )

  await query.execute(
    `CREATE TABLE IF NOT EXISTS "configurations" (
      "category" TEXT NOT NULL,
      "name" TEXT NOT NULL,
      "value" TEXT NOT NULL,
      "lastUpdatedAt" INTEGER NOT NULL DEFAULT CAST(EXTRACT(EPOCH FROM NOW()) AS INTEGER),
      PRIMARY KEY ("category", "name")
    )`
  )

  await query.execute(
    `CREATE TABLE IF NOT EXISTS "proxies" (
      "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      "protocol" TEXT NOT NULL,
      "host" TEXT NOT NULL,
      "port" INTEGER NOT NULL,
      "user" TEXT,
      "password" TEXT,
      "createdAt" INTEGER NOT NULL DEFAULT CAST(EXTRACT(EPOCH FROM NOW()) AS INTEGER)
    )`
  )
  await query.execute(
    `CREATE TABLE IF NOT EXISTS "mojangInstances" (
      "name" TEXT PRIMARY KEY,
      "proxyId" INTEGER REFERENCES "proxies"("id") ON DELETE SET NULL,
      "connect" INTEGER NOT NULL DEFAULT 1
    )`
  )
  await query.execute(
    `CREATE TABLE IF NOT EXISTS "mojangSessions" (
      "name" TEXT NOT NULL,
      "cacheName" TEXT NOT NULL,
      "value" TEXT NOT NULL,
      "createdAt" INTEGER NOT NULL,
      PRIMARY KEY ("name", "cacheName")
    )`
  )
  await query.execute(
    `CREATE TABLE IF NOT EXISTS "mojangProfileSettings" (
      "id" TEXT PRIMARY KEY,
      "playerOnlineStatusEnabled" INTEGER NOT NULL DEFAULT 0,
      "guildAllEnabled" INTEGER NOT NULL DEFAULT 0,
      "guildChatEnabled" INTEGER NOT NULL DEFAULT 0,
      "guildNotificationsEnabled" INTEGER NOT NULL DEFAULT 0,
      "selectedEnglish" INTEGER NOT NULL DEFAULT 0
    )`
  )

  await query.execute(
    `CREATE TABLE IF NOT EXISTS "discordLeaderboards" (
      "messageId" TEXT PRIMARY KEY,
      "type" TEXT NOT NULL,
      "channelId" TEXT NOT NULL,
      "guildId" TEXT,
      "updatedAt" INTEGER NOT NULL DEFAULT CAST(EXTRACT(EPOCH FROM NOW()) AS INTEGER),
      "createdAt" INTEGER NOT NULL DEFAULT CAST(EXTRACT(EPOCH FROM NOW()) AS INTEGER)
    )`
  )
  await query.execute(
    `CREATE TABLE IF NOT EXISTS "discordTempInteractions" (
      "messageId" TEXT PRIMARY KEY,
      "channelId" TEXT NOT NULL,
      "createdAt" INTEGER NOT NULL DEFAULT CAST(EXTRACT(EPOCH FROM NOW()) AS INTEGER)
    )`
  )
  await query.execute(
    `CREATE TABLE IF NOT EXISTS "discordEmojis" (
      "name" TEXT PRIMARY KEY,
      "hash" TEXT NOT NULL,
      "createdAt" INTEGER NOT NULL DEFAULT CAST(EXTRACT(EPOCH FROM NOW()) AS INTEGER)
    )`
  )

  await query.execute(
    `CREATE TABLE IF NOT EXISTS "minecraftBots" (
      "uuid" TEXT PRIMARY KEY,
      "updatedAt" INTEGER NOT NULL DEFAULT CAST(EXTRACT(EPOCH FROM NOW()) AS INTEGER),
      "createdAt" INTEGER NOT NULL DEFAULT CAST(EXTRACT(EPOCH FROM NOW()) AS INTEGER)
    )`
  )

  await query.execute(
    `CREATE TABLE IF NOT EXISTS "instanceStatusHistory" (
      "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      "instanceName" TEXT NOT NULL,
      "instanceType" TEXT NOT NULL,
      "fromStatus" TEXT NOT NULL,
      "toStatus" TEXT NOT NULL,
      "createdAt" INTEGER NOT NULL DEFAULT CAST(EXTRACT(EPOCH FROM NOW()) AS INTEGER)
    )`
  )
  await query.execute(
    `CREATE TABLE IF NOT EXISTS "instanceMessageHistory" (
      "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      "instanceName" TEXT NOT NULL,
      "instanceType" TEXT NOT NULL,
      "type" TEXT NOT NULL,
      "value" TEXT,
      "createdAt" INTEGER NOT NULL DEFAULT CAST(EXTRACT(EPOCH FROM NOW()) AS INTEGER)
    )`
  )

  await query.execute(
    `CREATE TABLE IF NOT EXISTS "discordInstanceHistoryButton" (
      "messageId" TEXT PRIMARY KEY,
      "channelId" TEXT NOT NULL,
      "instanceName" TEXT NOT NULL,
      "instanceType" TEXT NOT NULL,
      "type" TEXT NOT NULL,
      "startTime" INTEGER NOT NULL,
      "endTime" INTEGER NOT NULL,
      "createdAt" INTEGER NOT NULL DEFAULT CAST(EXTRACT(EPOCH FROM NOW()) AS INTEGER)
    )`
  )
  await query.execute(
    `CREATE TABLE IF NOT EXISTS "discordInstanceHistoryLastButton" (
      "messageId" TEXT NOT NULL,
      "channelId" TEXT NOT NULL,
      "instanceName" TEXT NOT NULL,
      "createdAt" INTEGER NOT NULL DEFAULT CAST(EXTRACT(EPOCH FROM NOW()) AS INTEGER),
      PRIMARY KEY ("channelId", "instanceName")
    )`
  )

  await query.execute(
    `CREATE TABLE IF NOT EXISTS "inactivity" (
      "uuid" TEXT PRIMARY KEY,
      "discordId" TEXT NOT NULL,
      "reason" TEXT NOT NULL,
      "createdAt" INTEGER NOT NULL,
      "expiresAt" INTEGER NOT NULL
    )`
  )
  await query.execute(`CREATE INDEX IF NOT EXISTS "inactivityDiscordId" ON "inactivity" ("discordId")`)
  await query.execute(`CREATE INDEX IF NOT EXISTS "inactivityExpiresAt" ON "inactivity" ("expiresAt")`)

  await query.execute(
    `CREATE TABLE IF NOT EXISTS "rankupPendingReviews" (
      "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      "bridgeId" TEXT NOT NULL,
      "uuid" TEXT NOT NULL,
      "currentRank" TEXT NOT NULL,
      "proposedRank" TEXT NOT NULL,
      "action" TEXT NOT NULL,
      "reason" TEXT NOT NULL,
      "createdAt" INTEGER NOT NULL DEFAULT CAST(EXTRACT(EPOCH FROM NOW()) AS INTEGER),
      "notifiedAt" INTEGER
    )`
  )
  await query.execute(`CREATE INDEX IF NOT EXISTS "rankupPendingBridge" ON "rankupPendingReviews" ("bridgeId")`)
  await query.execute(
    `CREATE UNIQUE INDEX IF NOT EXISTS "rankupPendingUnique" ON "rankupPendingReviews" ("bridgeId", "uuid")`
  )

  await query.execute(
    `CREATE TABLE IF NOT EXISTS "rankupHistory" (
      "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      "bridgeId" TEXT NOT NULL,
      "uuid" TEXT NOT NULL,
      "action" TEXT NOT NULL,
      "fromRank" TEXT NOT NULL,
      "toRank" TEXT NOT NULL,
      "triggeredBy" TEXT NOT NULL,
      "createdAt" INTEGER NOT NULL DEFAULT CAST(EXTRACT(EPOCH FROM NOW()) AS INTEGER)
    )`
  )
  await query.execute(`CREATE INDEX IF NOT EXISTS "rankupHistoryBridge" ON "rankupHistory" ("bridgeId")`)

  await query.execute(
    `CREATE TABLE IF NOT EXISTS "disconnectLogs" (
      "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      "instanceName" TEXT NOT NULL,
      "eventType" TEXT NOT NULL,
      "reason" TEXT NOT NULL,
      "createdAt" INTEGER NOT NULL DEFAULT CAST(EXTRACT(EPOCH FROM NOW()) AS INTEGER)
    )`
  )
  await query.execute(`CREATE INDEX IF NOT EXISTS "disconnectLogsInstanceName" ON "disconnectLogs" ("instanceName")`)
  await query.execute(`CREATE INDEX IF NOT EXISTS "disconnectLogsCreatedAt" ON "disconnectLogs" ("createdAt")`)
}

export async function down(query: QueryInterface): Promise<void> {
  const tables = [
    'disconnectLogs',
    'rankupHistory',
    'rankupPendingReviews',
    'inactivity',
    'discordInstanceHistoryLastButton',
    'discordInstanceHistoryButton',
    'instanceMessageHistory',
    'instanceStatusHistory',
    'minecraftBots',
    'discordEmojis',
    'discordTempInteractions',
    'discordLeaderboards',
    'mojangProfileSettings',
    'mojangSessions',
    'mojangInstances',
    'proxies',
    'configurations',
    'autocompleteRanks',
    'autocompleteUsernames',
    'heatsCommandsWarnings',
    'heatsCommands',
    'punishments',
    'guildMemberDailySnapshots',
    'guildMemberEvents',
    'guildMemberStates',
    'OnlineMembers',
    'AllMembers',
    'MinecraftCommands',
    'DiscordCommands',
    'MinecraftMessages',
    'DiscordMessages',
    'links',
    'mojang'
  ]

  for (const table of tables) {
    await query.execute(`DROP TABLE IF EXISTS "${table}" CASCADE`)
  }
}
