import type { QueryInterface } from '../runner.js'

export async function up(query: QueryInterface): Promise<void> {
  await query.execute(
    `CREATE TABLE IF NOT EXISTS "commandErrors" (
      "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      "commandName" TEXT NOT NULL,
      "commandMessage" TEXT NOT NULL,
      "username" TEXT NOT NULL,
      "instanceName" TEXT NOT NULL,
      "instanceType" TEXT NOT NULL,
      "bridgeId" TEXT,
      "errorType" TEXT,
      "errorMessage" TEXT,
      "errorStack" TEXT,
      "createdAt" INTEGER NOT NULL DEFAULT CAST(EXTRACT(EPOCH FROM NOW()) AS INTEGER)
    )`
  )
  await query.execute(`CREATE INDEX IF NOT EXISTS "commandErrorsCommandName" ON "commandErrors" ("commandName")`)
  await query.execute(`CREATE INDEX IF NOT EXISTS "commandErrorsCreatedAt" ON "commandErrors" ("createdAt")`)
}

export async function down(query: QueryInterface): Promise<void> {
  await query.execute(`DROP TABLE IF EXISTS "commandErrors" CASCADE`)
}
