import type { QueryInterface } from '../runner.js'

export async function up(query: QueryInterface): Promise<void> {
  await query.execute(
    `CREATE TABLE IF NOT EXISTS "statMonitors" (
      "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      "ownerId" TEXT NOT NULL,
      "playerUuid" TEXT NOT NULL,
      "playerName" TEXT NOT NULL,
      "game" TEXT NOT NULL,
      "stat" TEXT NOT NULL,
      "lastValue" DOUBLE PRECISION,
      "threshold" DOUBLE PRECISION,
      "bridgeId" TEXT,
      "createdAt" INTEGER NOT NULL DEFAULT CAST(EXTRACT(EPOCH FROM NOW()) AS INTEGER),
      UNIQUE ("ownerId", "playerUuid", "game", "stat")
    )`
  )
  await query.execute(`ALTER TABLE "statMonitors" ADD COLUMN IF NOT EXISTS "threshold" DOUBLE PRECISION`)
  await query.execute(`CREATE INDEX IF NOT EXISTS "statMonitorsOwnerIndex" ON "statMonitors" ("ownerId")`)
  await query.execute(`CREATE INDEX IF NOT EXISTS "statMonitorsPlayerIndex" ON "statMonitors" ("playerUuid")`)
}

export async function down(query: QueryInterface): Promise<void> {
  await query.execute(`DROP TABLE IF EXISTS "statMonitors" CASCADE`)
}
