import type { QueryInterface } from '../runner.js'

export async function up(query: QueryInterface): Promise<void> {
  await query.execute(
    `CREATE TABLE IF NOT EXISTS "ChatMessages" (
      "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      "userId" TEXT NOT NULL,
      "message" TEXT NOT NULL,
      "createdAt" INTEGER NOT NULL DEFAULT CAST(EXTRACT(EPOCH FROM NOW()) AS INTEGER)
    )`
  )
  await query.execute(`CREATE INDEX IF NOT EXISTS "chatMessagesUserId" ON "ChatMessages" ("userId", "createdAt" DESC)`)

  await query.execute(
    `CREATE TABLE IF NOT EXISTS "IqScores" (
      "userId" TEXT PRIMARY KEY,
      "iq" INTEGER NOT NULL,
      "calculatedAt" INTEGER NOT NULL
    )`
  )
}

export async function down(query: QueryInterface): Promise<void> {
  await query.execute(`DROP TABLE IF EXISTS "IqScores"`)
  await query.execute(`DROP TABLE IF EXISTS "ChatMessages" CASCADE`)
}
