import type { QueryInterface } from '../runner.js'

export async function up(query: QueryInterface): Promise<void> {
  await query.execute(
    `CREATE TABLE IF NOT EXISTS "tournaments" (
      "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      "bridgeId" TEXT NOT NULL,
      "name" TEXT NOT NULL,
      "gameType" TEXT NOT NULL,
      "bestOf" INTEGER NOT NULL DEFAULT 1,
      "status" TEXT NOT NULL DEFAULT 'SIGNUP',
      "roundDeadlineHours" INTEGER NOT NULL DEFAULT 48,
      "createdBy" TEXT NOT NULL,
      "winnerId" INTEGER,
      "discordChannelId" TEXT,
      "bracketMessageId" TEXT,
      "currentRound" INTEGER NOT NULL DEFAULT 0,
      "totalRounds" INTEGER NOT NULL DEFAULT 0,
      "createdAt" INTEGER NOT NULL DEFAULT CAST(EXTRACT(EPOCH FROM NOW()) AS INTEGER),
      "startedAt" INTEGER,
      "completedAt" INTEGER
    )`
  )
  await query.execute(`CREATE INDEX IF NOT EXISTS "idx_tournaments_bridgeId" ON "tournaments" ("bridgeId")`)
  await query.execute(`CREATE INDEX IF NOT EXISTS "idx_tournaments_status" ON "tournaments" ("status")`)

  await query.execute(
    `CREATE TABLE IF NOT EXISTS "tournament_players" (
      "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      "tournamentId" INTEGER NOT NULL REFERENCES "tournaments"("id") ON DELETE CASCADE,
      "playerUuid" TEXT NOT NULL,
      "discordId" TEXT,
      "seed" INTEGER NOT NULL DEFAULT 0,
      "status" TEXT NOT NULL DEFAULT 'REGISTERED',
      "joinedAt" INTEGER NOT NULL DEFAULT CAST(EXTRACT(EPOCH FROM NOW()) AS INTEGER),
      UNIQUE("tournamentId", "playerUuid")
    )`
  )
  await query.execute(`CREATE INDEX IF NOT EXISTS "idx_tplayers_tournamentId" ON "tournament_players" ("tournamentId")`)

  await query.execute(
    `ALTER TABLE "tournaments" ADD CONSTRAINT "fk_tournaments_winner" FOREIGN KEY ("winnerId") REFERENCES "tournament_players" ("id") ON DELETE SET NULL`
  )

  await query.execute(
    `CREATE TABLE IF NOT EXISTS "tournament_matches" (
      "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      "tournamentId" INTEGER NOT NULL REFERENCES "tournaments"("id") ON DELETE CASCADE,
      "round" INTEGER NOT NULL,
      "matchIndex" INTEGER NOT NULL,
      "player1Id" INTEGER REFERENCES "tournament_players"("id") ON DELETE SET NULL,
      "player2Id" INTEGER REFERENCES "tournament_players"("id") ON DELETE SET NULL,
      "winnerId" INTEGER REFERENCES "tournament_players"("id") ON DELETE SET NULL,
      "nextMatchId" INTEGER REFERENCES "tournament_matches"("id") ON DELETE SET NULL,
      "status" TEXT NOT NULL DEFAULT 'PENDING',
      "player1Wins" INTEGER NOT NULL DEFAULT 0,
      "player2Wins" INTEGER NOT NULL DEFAULT 0,
      "discordThreadId" TEXT,
      "deadlineAt" INTEGER,
      "warningsSent" INTEGER NOT NULL DEFAULT 0,
      "completedAt" INTEGER,
      UNIQUE("tournamentId", "round", "matchIndex")
    )`
  )
  await query.execute(`CREATE INDEX IF NOT EXISTS "idx_tmatches_tournamentId" ON "tournament_matches" ("tournamentId")`)
  await query.execute(`CREATE INDEX IF NOT EXISTS "idx_tmatches_status" ON "tournament_matches" ("status")`)
  await query.execute(`CREATE INDEX IF NOT EXISTS "idx_tmatches_deadlineAt" ON "tournament_matches" ("deadlineAt")`)

  await query.execute(
    `CREATE TABLE IF NOT EXISTS "tournament_reports" (
      "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      "matchId" INTEGER NOT NULL REFERENCES "tournament_matches"("id") ON DELETE CASCADE,
      "reporterId" INTEGER NOT NULL REFERENCES "tournament_players"("id") ON DELETE CASCADE,
      "claimedWinnerId" INTEGER NOT NULL REFERENCES "tournament_players"("id") ON DELETE CASCADE,
      "player1Wins" INTEGER NOT NULL DEFAULT 0,
      "player2Wins" INTEGER NOT NULL DEFAULT 0,
      "createdAt" INTEGER NOT NULL DEFAULT CAST(EXTRACT(EPOCH FROM NOW()) AS INTEGER),
      UNIQUE("matchId", "reporterId")
    )`
  )
  await query.execute(`CREATE INDEX IF NOT EXISTS "idx_treports_matchId" ON "tournament_reports" ("matchId")`)
}

export async function down(query: QueryInterface): Promise<void> {
  await query.execute(`ALTER TABLE "tournaments" DROP CONSTRAINT IF EXISTS "fk_tournaments_winner"`)
  await query.execute(`DROP TABLE IF EXISTS "tournament_reports" CASCADE`)
  await query.execute(`DROP TABLE IF EXISTS "tournament_matches" CASCADE`)
  await query.execute(`DROP TABLE IF EXISTS "tournament_players" CASCADE`)
  await query.execute(`DROP TABLE IF EXISTS "tournaments" CASCADE`)
}
