import type { QueryInterface } from '../runner.js'

export async function up(query: QueryInterface): Promise<void> {
  await query.execute(
    `CREATE TABLE IF NOT EXISTS "tournament_audit_log" (
      "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      "tournamentId" INTEGER NOT NULL REFERENCES "tournaments"("id") ON DELETE CASCADE,
      "action" TEXT NOT NULL,
      "actorDiscordId" TEXT NOT NULL,
      "targetMatchId" INTEGER REFERENCES "tournament_matches"("id") ON DELETE SET NULL,
      "targetUuid" TEXT,
      "metadata" JSONB,
      "createdAt" INTEGER NOT NULL DEFAULT CAST(EXTRACT(EPOCH FROM NOW()) AS INTEGER)
    )`
  )
  await query.execute(
    `CREATE INDEX IF NOT EXISTS "idx_auditlog_tournamentId" ON "tournament_audit_log" ("tournamentId")`
  )
  await query.execute(`CREATE INDEX IF NOT EXISTS "idx_auditlog_action" ON "tournament_audit_log" ("action")`)
}

export async function down(query: QueryInterface): Promise<void> {
  await query.execute(`DROP TABLE IF EXISTS "tournament_audit_log" CASCADE`)
}
