import type { QueryInterface } from '../runner.js'

const RemovedTables = [
  'DiscordMessages',
  'MinecraftMessages',
  'DiscordCommands',
  'MinecraftCommands',
  'AllMembers',
  'OnlineMembers',
  'guildMemberEvents',
  'guildMemberDailySnapshots',
  'punishments',
  'heatsCommands',
  'heatsCommandsWarnings',
  'commandErrors',
  'proxies',
  'minecraftBots',
  'inactivity',
  'disconnectLogs',
  'discordLeaderboards'
]

export async function up(query: QueryInterface): Promise<void> {
  for (const table of RemovedTables) {
    await query.execute(`DROP TABLE IF EXISTS "${table}" CASCADE`)
  }
  await query.execute(`ALTER TABLE "mojangInstances" DROP COLUMN IF EXISTS "proxyId"`)
}

export async function down(query: QueryInterface): Promise<void> {
  await query.execute(
    `CREATE TABLE IF NOT EXISTS "DiscordMessages" (
      "timestamp" INTEGER NOT NULL,
      "user" TEXT NOT NULL,
      "count" INTEGER NOT NULL DEFAULT 0,
      PRIMARY KEY ("timestamp", "user")
    )`
  )
  await query.execute(
    `CREATE TABLE IF NOT EXISTS "MinecraftMessages" (
      "timestamp" INTEGER NOT NULL,
      "user" TEXT NOT NULL,
      "count" INTEGER NOT NULL DEFAULT 0,
      PRIMARY KEY ("timestamp", "user")
    )`
  )
  await query.execute(
    `CREATE TABLE IF NOT EXISTS "DiscordCommands" (
      "timestamp" INTEGER NOT NULL,
      "user" TEXT NOT NULL,
      "count" INTEGER NOT NULL DEFAULT 0,
      PRIMARY KEY ("timestamp", "user")
    )`
  )
  await query.execute(
    `CREATE TABLE IF NOT EXISTS "MinecraftCommands" (
      "timestamp" INTEGER NOT NULL,
      "user" TEXT NOT NULL,
      "count" INTEGER NOT NULL DEFAULT 0,
      PRIMARY KEY ("timestamp", "user")
    )`
  )
  await query.execute(
    `CREATE TABLE IF NOT EXISTS "AllMembers" (
      "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      "uuid" TEXT NOT NULL,
      "fromTimestamp" INTEGER NOT NULL,
      "toTimestamp" INTEGER NOT NULL,
      CHECK ("fromTimestamp" <= "toTimestamp")
    )`
  )
  await query.execute(
    `CREATE TABLE IF NOT EXISTS "OnlineMembers" (
      "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      "uuid" TEXT NOT NULL,
      "fromTimestamp" INTEGER NOT NULL,
      "toTimestamp" INTEGER NOT NULL,
      CHECK ("fromTimestamp" <= "toTimestamp")
    )`
  )
  await query.execute(
    `CREATE TABLE IF NOT EXISTS "guildMemberEvents" (
      "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      "instanceName" TEXT NOT NULL,
      "memberUuid" TEXT NOT NULL,
      "memberName" TEXT NOT NULL,
      "eventType" TEXT NOT NULL,
      "rank" TEXT NOT NULL,
      "weeklyGexp" INTEGER NOT NULL,
      "dailyGexp" INTEGER NOT NULL,
      "online" INTEGER NOT NULL,
      "createdAt" INTEGER NOT NULL DEFAULT CAST(EXTRACT(EPOCH FROM NOW()) AS INTEGER)
    )`
  )
  await query.execute(
    `CREATE TABLE IF NOT EXISTS "guildMemberDailySnapshots" (
      "snapshotDay" INTEGER NOT NULL,
      "instanceName" TEXT NOT NULL,
      "memberUuid" TEXT NOT NULL,
      "memberName" TEXT NOT NULL,
      "joinedAt" INTEGER NOT NULL,
      "lastSeenAt" INTEGER NOT NULL,
      "weeklyGexp" INTEGER NOT NULL,
      "dailyGexp" INTEGER NOT NULL,
      "online" INTEGER NOT NULL,
      PRIMARY KEY ("snapshotDay", "instanceName", "memberUuid")
    )`
  )
  await query.execute(
    `CREATE TABLE IF NOT EXISTS "punishments" (
      "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      "originInstance" TEXT NOT NULL,
      "userId" TEXT NOT NULL,
      "type" TEXT NOT NULL,
      "purpose" TEXT NOT NULL,
      "reason" TEXT NOT NULL,
      "createdAt" INTEGER NOT NULL,
      "till" INTEGER NOT NULL
    )`
  )
  await query.execute(
    `CREATE TABLE IF NOT EXISTS "heatsCommands" (
      "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      "originInstance" TEXT NOT NULL,
      "userId" TEXT NOT NULL,
      "type" TEXT NOT NULL,
      "createdAt" INTEGER NOT NULL
    )`
  )
  await query.execute(
    `CREATE TABLE IF NOT EXISTS "heatsCommandsWarnings" (
      "originInstance" TEXT NOT NULL,
      "userId" TEXT NOT NULL,
      "type" TEXT NOT NULL,
      "warnedAt" INTEGER NOT NULL,
      PRIMARY KEY ("originInstance", "userId", "type")
    )`
  )
  await query.execute(
    `CREATE TABLE IF NOT EXISTS "commandErrors" (
      "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      "commandName" TEXT NOT NULL,
      "commandMessage" TEXT NOT NULL,
      "username" TEXT NOT NULL,
      "instanceName" TEXT NOT NULL,
      "instanceType" TEXT NOT NULL,
      "bridgeId" TEXT,
      "errorType" TEXT,
      "errorMessage" TEXT,
      "errorStack" TEXT,
      "createdAt" INTEGER NOT NULL DEFAULT CAST(EXTRACT(EPOCH FROM NOW()) AS INTEGER)
    )`
  )
  await query.execute(
    `CREATE TABLE IF NOT EXISTS "proxies" (
      "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      "protocol" TEXT NOT NULL,
      "host" TEXT NOT NULL,
      "port" INTEGER NOT NULL,
      "user" TEXT,
      "password" TEXT,
      "createdAt" INTEGER NOT NULL DEFAULT CAST(EXTRACT(EPOCH FROM NOW()) AS INTEGER)
    )`
  )
  await query.execute(
    `CREATE TABLE IF NOT EXISTS "minecraftBots" (
      "uuid" TEXT PRIMARY KEY,
      "updatedAt" INTEGER NOT NULL DEFAULT CAST(EXTRACT(EPOCH FROM NOW()) AS INTEGER),
      "createdAt" INTEGER NOT NULL DEFAULT CAST(EXTRACT(EPOCH FROM NOW()) AS INTEGER)
    )`
  )
  await query.execute(
    `CREATE TABLE IF NOT EXISTS "inactivity" (
      "uuid" TEXT PRIMARY KEY,
      "discordId" TEXT NOT NULL,
      "reason" TEXT NOT NULL,
      "createdAt" INTEGER NOT NULL,
      "expiresAt" INTEGER NOT NULL
    )`
  )
  await query.execute(
    `CREATE TABLE IF NOT EXISTS "disconnectLogs" (
      "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      "instanceName" TEXT NOT NULL,
      "eventType" TEXT NOT NULL,
      "reason" TEXT NOT NULL,
      "createdAt" INTEGER NOT NULL DEFAULT CAST(EXTRACT(EPOCH FROM NOW()) AS INTEGER)
    )`
  )
  await query.execute(
    `CREATE TABLE IF NOT EXISTS "discordLeaderboards" (
      "messageId" TEXT PRIMARY KEY,
      "type" TEXT NOT NULL,
      "channelId" TEXT NOT NULL,
      "guildId" TEXT,
      "updatedAt" INTEGER NOT NULL DEFAULT CAST(EXTRACT(EPOCH FROM NOW()) AS INTEGER),
      "createdAt" INTEGER NOT NULL DEFAULT CAST(EXTRACT(EPOCH FROM NOW()) AS INTEGER)
    )`
  )
  await query.execute(`ALTER TABLE "mojangInstances" ADD COLUMN IF NOT EXISTS "proxyId" INTEGER`)
}
