import type { QueryInterface } from '../runner.js'

export async function up(query: QueryInterface): Promise<void> {
  await query.execute(
    `CREATE TABLE IF NOT EXISTS "tournament_match_proofs" (
      "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      "matchId" INTEGER NOT NULL REFERENCES "tournament_matches"("id") ON DELETE CASCADE,
      "tournamentId" INTEGER NOT NULL REFERENCES "tournaments"("id") ON DELETE CASCADE,
      "playerUuid" TEXT NOT NULL,
      "discordId" TEXT,
      "url" TEXT NOT NULL,
      "createdAt" INTEGER NOT NULL DEFAULT CAST(EXTRACT(EPOCH FROM NOW()) AS INTEGER)
    )`
  )
  await query.execute(`CREATE INDEX IF NOT EXISTS "idx_tproofs_matchId" ON "tournament_match_proofs" ("matchId")`)
  await query.execute(
    `CREATE INDEX IF NOT EXISTS "idx_tproofs_tournamentId" ON "tournament_match_proofs" ("tournamentId")`
  )
}

export async function down(query: QueryInterface): Promise<void> {
  await query.execute(`DROP TABLE IF EXISTS "tournament_match_proofs" CASCADE`)
}
