import type { QueryInterface } from '../runner.js'

export async function up(query: QueryInterface): Promise<void> {
  await query.execute(`DROP TABLE IF EXISTS "instanceMessageHistory" CASCADE`)
}

export async function down(query: QueryInterface): Promise<void> {
  await query.execute(
    `CREATE TABLE IF NOT EXISTS "instanceMessageHistory" (
      "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      "instanceName" TEXT NOT NULL,
      "instanceType" TEXT NOT NULL,
      "type" TEXT NOT NULL,
      "value" TEXT,
      "createdAt" INTEGER NOT NULL DEFAULT CAST(EXTRACT(EPOCH FROM NOW()) AS INTEGER)
    )`
  )
}
