import type { DatabaseManager } from '../common/database-manager'

const SchemaStatements = [
  `CREATE TABLE IF NOT EXISTS "mojang" (
    "uuid" TEXT PRIMARY KEY,
    "username" TEXT NOT NULL,
    "loweredName" TEXT NOT NULL,
    "createdAt" INTEGER NOT NULL DEFAULT CAST(EXTRACT(EPOCH FROM NOW()) AS INTEGER)
  )`,
  `CREATE UNIQUE INDEX IF NOT EXISTS "mojangLoweredNameUnique" ON "mojang" ("loweredName")`,

  `CREATE TABLE IF NOT EXISTS "links" (
    "uuid" TEXT PRIMARY KEY,
    "discordId" TEXT NOT NULL UNIQUE,
    "createdAt" INTEGER NOT NULL DEFAULT CAST(EXTRACT(EPOCH FROM NOW()) AS INTEGER)
  )`,

  `CREATE TABLE IF NOT EXISTS "DiscordMessages" (
    "timestamp" INTEGER NOT NULL,
    "user" TEXT NOT NULL,
    "count" INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY ("timestamp", "user")
  )`,
  `CREATE TABLE IF NOT EXISTS "MinecraftMessages" (
    "timestamp" INTEGER NOT NULL,
    "user" TEXT NOT NULL,
    "count" INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY ("timestamp", "user")
  )`,
  `CREATE TABLE IF NOT EXISTS "DiscordCommands" (
    "timestamp" INTEGER NOT NULL,
    "user" TEXT NOT NULL,
    "count" INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY ("timestamp", "user")
  )`,
  `CREATE TABLE IF NOT EXISTS "MinecraftCommands" (
    "timestamp" INTEGER NOT NULL,
    "user" TEXT NOT NULL,
    "count" INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY ("timestamp", "user")
  )`,

  `CREATE TABLE IF NOT EXISTS "AllMembers" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "uuid" TEXT NOT NULL,
    "fromTimestamp" INTEGER NOT NULL,
    "toTimestamp" INTEGER NOT NULL,
    CHECK ("fromTimestamp" <= "toTimestamp")
  )`,
  `CREATE TABLE IF NOT EXISTS "OnlineMembers" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "uuid" TEXT NOT NULL,
    "fromTimestamp" INTEGER NOT NULL,
    "toTimestamp" INTEGER NOT NULL,
    CHECK ("fromTimestamp" <= "toTimestamp")
  )`,
  `CREATE INDEX IF NOT EXISTS "allMembersUuidIndex" ON "AllMembers" ("uuid", "fromTimestamp", "toTimestamp")`,
  `CREATE INDEX IF NOT EXISTS "onlineMembersUuidIndex" ON "OnlineMembers" ("uuid", "fromTimestamp", "toTimestamp")`,

  `CREATE TABLE IF NOT EXISTS "punishments" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "originInstance" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "type" TEXT NOT NULL,
    "purpose" TEXT NOT NULL,
    "reason" TEXT NOT NULL,
    "createdAt" INTEGER NOT NULL,
    "till" INTEGER NOT NULL
  )`,
  `CREATE INDEX IF NOT EXISTS "punishmentsIndex" ON "punishments" ("originInstance", "userId")`,

  `CREATE TABLE IF NOT EXISTS "heatsCommands" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "originInstance" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "type" TEXT NOT NULL,
    "createdAt" INTEGER NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS "heatsCommandsWarnings" (
    "originInstance" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "type" TEXT NOT NULL,
    "warnedAt" INTEGER NOT NULL,
    PRIMARY KEY ("originInstance", "userId", "type")
  )`,
  `CREATE INDEX IF NOT EXISTS "heatsCommandsIndex" ON "heatsCommands" ("originInstance", "userId")`,

  `CREATE TABLE IF NOT EXISTS "autocompleteUsernames" (
    "loweredContent" TEXT PRIMARY KEY,
    "content" TEXT NOT NULL,
    "timestamp" INTEGER NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS "autocompleteRanks" (
    "loweredContent" TEXT PRIMARY KEY,
    "content" TEXT NOT NULL,
    "timestamp" INTEGER NOT NULL
  )`,

  `CREATE TABLE IF NOT EXISTS "configurations" (
    "category" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "value" TEXT NOT NULL,
    "lastUpdatedAt" INTEGER NOT NULL DEFAULT CAST(EXTRACT(EPOCH FROM NOW()) AS INTEGER),
    PRIMARY KEY ("category", "name")
  )`,

  `CREATE TABLE IF NOT EXISTS "proxies" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "protocol" TEXT NOT NULL,
    "host" TEXT NOT NULL,
    "port" INTEGER NOT NULL,
    "user" TEXT,
    "password" TEXT,
    "createdAt" INTEGER NOT NULL DEFAULT CAST(EXTRACT(EPOCH FROM NOW()) AS INTEGER)
  )`,
  `CREATE TABLE IF NOT EXISTS "mojangInstances" (
    "name" TEXT PRIMARY KEY,
    "proxyId" INTEGER REFERENCES "proxies"("id") ON DELETE SET NULL,
    "connect" INTEGER NOT NULL DEFAULT 1
  )`,
  `CREATE TABLE IF NOT EXISTS "mojangSessions" (
    "name" TEXT NOT NULL,
    "cacheName" TEXT NOT NULL,
    "value" TEXT NOT NULL,
    "createdAt" INTEGER NOT NULL,
    PRIMARY KEY ("name", "cacheName")
  )`,
  `CREATE TABLE IF NOT EXISTS "mojangProfileSettings" (
    "id" TEXT PRIMARY KEY,
    "playerOnlineStatusEnabled" INTEGER NOT NULL DEFAULT 0,
    "guildAllEnabled" INTEGER NOT NULL DEFAULT 0,
    "guildChatEnabled" INTEGER NOT NULL DEFAULT 0,
    "guildNotificationsEnabled" INTEGER NOT NULL DEFAULT 0,
    "selectedEnglish" INTEGER NOT NULL DEFAULT 0
  )`,

  `CREATE TABLE IF NOT EXISTS "discordLeaderboards" (
    "messageId" TEXT PRIMARY KEY,
    "type" TEXT NOT NULL,
    "channelId" TEXT NOT NULL,
    "guildId" TEXT,
    "updatedAt" INTEGER NOT NULL DEFAULT CAST(EXTRACT(EPOCH FROM NOW()) AS INTEGER),
    "createdAt" INTEGER NOT NULL DEFAULT CAST(EXTRACT(EPOCH FROM NOW()) AS INTEGER)
  )`,
  `CREATE TABLE IF NOT EXISTS "discordTempInteractions" (
    "messageId" TEXT PRIMARY KEY,
    "channelId" TEXT NOT NULL,
    "createdAt" INTEGER NOT NULL DEFAULT CAST(EXTRACT(EPOCH FROM NOW()) AS INTEGER)
  )`,
  `CREATE TABLE IF NOT EXISTS "discordEmojis" (
    "name" TEXT PRIMARY KEY,
    "hash" TEXT NOT NULL,
    "createdAt" INTEGER NOT NULL DEFAULT CAST(EXTRACT(EPOCH FROM NOW()) AS INTEGER)
  )`,

  `CREATE TABLE IF NOT EXISTS "minecraftBots" (
    "uuid" TEXT PRIMARY KEY,
    "updatedAt" INTEGER NOT NULL DEFAULT CAST(EXTRACT(EPOCH FROM NOW()) AS INTEGER),
    "createdAt" INTEGER NOT NULL DEFAULT CAST(EXTRACT(EPOCH FROM NOW()) AS INTEGER)
  )`,

  `CREATE TABLE IF NOT EXISTS "instanceStatusHistory" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "instanceName" TEXT NOT NULL,
    "instanceType" TEXT NOT NULL,
    "fromStatus" TEXT NOT NULL,
    "toStatus" TEXT NOT NULL,
    "createdAt" INTEGER NOT NULL DEFAULT CAST(EXTRACT(EPOCH FROM NOW()) AS INTEGER)
  )`,
  `CREATE TABLE IF NOT EXISTS "instanceMessageHistory" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "instanceName" TEXT NOT NULL,
    "instanceType" TEXT NOT NULL,
    "type" TEXT NOT NULL,
    "value" TEXT,
    "createdAt" INTEGER NOT NULL DEFAULT CAST(EXTRACT(EPOCH FROM NOW()) AS INTEGER)
  )`,

  `CREATE TABLE IF NOT EXISTS "discordInstanceHistoryButton" (
    "messageId" TEXT PRIMARY KEY,
    "channelId" TEXT NOT NULL,
    "instanceName" TEXT NOT NULL,
    "instanceType" TEXT NOT NULL,
    "type" TEXT NOT NULL,
    "startTime" INTEGER NOT NULL,
    "endTime" INTEGER NOT NULL,
    "createdAt" INTEGER NOT NULL DEFAULT CAST(EXTRACT(EPOCH FROM NOW()) AS INTEGER)
  )`,
  `CREATE TABLE IF NOT EXISTS "discordInstanceHistoryLastButton" (
    "messageId" TEXT NOT NULL,
    "channelId" TEXT NOT NULL,
    "instanceName" TEXT NOT NULL,
    "createdAt" INTEGER NOT NULL DEFAULT CAST(EXTRACT(EPOCH FROM NOW()) AS INTEGER),
    PRIMARY KEY ("channelId", "instanceName")
  )`,

  `CREATE TABLE IF NOT EXISTS "inactivity" (
    "uuid" TEXT PRIMARY KEY,
    "discordId" TEXT NOT NULL,
    "reason" TEXT NOT NULL,
    "createdAt" INTEGER NOT NULL,
    "expiresAt" INTEGER NOT NULL
  )`,
  `CREATE INDEX IF NOT EXISTS "inactivityDiscordId" ON "inactivity" ("discordId")`,
  `CREATE INDEX IF NOT EXISTS "inactivityExpiresAt" ON "inactivity" ("expiresAt")`,

  `CREATE TABLE IF NOT EXISTS "rankupPendingReviews" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "bridgeId" TEXT NOT NULL,
    "uuid" TEXT NOT NULL,
    "currentRank" TEXT NOT NULL,
    "proposedRank" TEXT NOT NULL,
    "action" TEXT NOT NULL,
    "reason" TEXT NOT NULL,
    "createdAt" INTEGER NOT NULL DEFAULT CAST(EXTRACT(EPOCH FROM NOW()) AS INTEGER),
    "notifiedAt" INTEGER
  )`,
  `CREATE INDEX IF NOT EXISTS "rankupPendingBridge" ON "rankupPendingReviews" ("bridgeId")`,
  `CREATE UNIQUE INDEX IF NOT EXISTS "rankupPendingUnique" ON "rankupPendingReviews" ("bridgeId", "uuid")`,

  `CREATE TABLE IF NOT EXISTS "rankupHistory" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "bridgeId" TEXT NOT NULL,
    "uuid" TEXT NOT NULL,
    "action" TEXT NOT NULL,
    "fromRank" TEXT NOT NULL,
    "toRank" TEXT NOT NULL,
    "triggeredBy" TEXT NOT NULL,
    "createdAt" INTEGER NOT NULL DEFAULT CAST(EXTRACT(EPOCH FROM NOW()) AS INTEGER)
  )`,
  `CREATE INDEX IF NOT EXISTS "rankupHistoryBridge" ON "rankupHistory" ("bridgeId")`,
  `CREATE INDEX IF NOT EXISTS "rankupHistoryUuid" ON "rankupHistory" ("uuid")`
]

/**
 * Applied after the main schema loop so databases that were initialized before
 * disconnectLogs existed still get the table on upgrade (idempotent).
 */
const DisconnectLogsSchemaStatements = [
  `CREATE TABLE IF NOT EXISTS "disconnectLogs" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "instanceName" TEXT NOT NULL,
    "eventType" TEXT NOT NULL,
    "reason" TEXT NOT NULL,
    "createdAt" INTEGER NOT NULL DEFAULT CAST(EXTRACT(EPOCH FROM NOW()) AS INTEGER)
  )`,
  `CREATE INDEX IF NOT EXISTS "disconnectLogsInstanceName" ON "disconnectLogs" ("instanceName")`,
  `CREATE INDEX IF NOT EXISTS "disconnectLogsCreatedAt" ON "disconnectLogs" ("createdAt")`
] as const

export async function initializeCoreDatabase(databaseManager: DatabaseManager): Promise<void> {
  await databaseManager.awaitReady()

  for (const statement of SchemaStatements) {
    await databaseManager.execute(statement)
  }

  for (const statement of DisconnectLogsSchemaStatements) {
    await databaseManager.execute(statement)
  }
}
