import fs from 'node:fs'

import type Application from '../application'
import type { SqliteManager } from '../common/sqlite-manager'

const SchemaStatements = [
  `CREATE TABLE IF NOT EXISTS "mojang" (
    "uuid" TEXT PRIMARY KEY,
    "username" TEXT NOT NULL,
    "loweredName" TEXT NOT NULL,
    "createdAt" INTEGER NOT NULL DEFAULT CAST(EXTRACT(EPOCH FROM NOW()) AS INTEGER)
  )`,
  `CREATE UNIQUE INDEX IF NOT EXISTS "mojangLoweredNameUnique" ON "mojang" ("loweredName")`,

  `CREATE TABLE IF NOT EXISTS "links" (
    "uuid" TEXT PRIMARY KEY,
    "discordId" TEXT NOT NULL UNIQUE,
    "createdAt" INTEGER NOT NULL DEFAULT CAST(EXTRACT(EPOCH FROM NOW()) AS INTEGER)
  )`,

  `CREATE TABLE IF NOT EXISTS "DiscordMessages" (
    "timestamp" INTEGER NOT NULL,
    "user" TEXT NOT NULL,
    "count" INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY ("timestamp", "user")
  )`,
  `CREATE TABLE IF NOT EXISTS "MinecraftMessages" (
    "timestamp" INTEGER NOT NULL,
    "user" TEXT NOT NULL,
    "count" INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY ("timestamp", "user")
  )`,
  `CREATE TABLE IF NOT EXISTS "DiscordCommands" (
    "timestamp" INTEGER NOT NULL,
    "user" TEXT NOT NULL,
    "count" INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY ("timestamp", "user")
  )`,
  `CREATE TABLE IF NOT EXISTS "MinecraftCommands" (
    "timestamp" INTEGER NOT NULL,
    "user" TEXT NOT NULL,
    "count" INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY ("timestamp", "user")
  )`,

  `CREATE TABLE IF NOT EXISTS "AllMembers" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "uuid" TEXT NOT NULL,
    "fromTimestamp" INTEGER NOT NULL,
    "toTimestamp" INTEGER NOT NULL,
    CHECK ("fromTimestamp" <= "toTimestamp")
  )`,
  `CREATE TABLE IF NOT EXISTS "OnlineMembers" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "uuid" TEXT NOT NULL,
    "fromTimestamp" INTEGER NOT NULL,
    "toTimestamp" INTEGER NOT NULL,
    CHECK ("fromTimestamp" <= "toTimestamp")
  )`,
  `CREATE INDEX IF NOT EXISTS "allMembersUuidIndex" ON "AllMembers" ("uuid", "fromTimestamp", "toTimestamp")`,
  `CREATE INDEX IF NOT EXISTS "onlineMembersUuidIndex" ON "OnlineMembers" ("uuid", "fromTimestamp", "toTimestamp")`,

  `CREATE TABLE IF NOT EXISTS "punishments" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "originInstance" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "type" TEXT NOT NULL,
    "purpose" TEXT NOT NULL,
    "reason" TEXT NOT NULL,
    "createdAt" INTEGER NOT NULL,
    "till" INTEGER NOT NULL
  )`,
  `CREATE INDEX IF NOT EXISTS "punishmentsIndex" ON "punishments" ("originInstance", "userId")`,

  `CREATE TABLE IF NOT EXISTS "heatsCommands" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "originInstance" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "type" TEXT NOT NULL,
    "createdAt" INTEGER NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS "heatsCommandsWarnings" (
    "originInstance" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "type" TEXT NOT NULL,
    "warnedAt" INTEGER NOT NULL,
    PRIMARY KEY ("originInstance", "userId", "type")
  )`,
  `CREATE INDEX IF NOT EXISTS "heatsCommandsIndex" ON "heatsCommands" ("originInstance", "userId")`,

  `CREATE TABLE IF NOT EXISTS "autocompleteUsernames" (
    "loweredContent" TEXT PRIMARY KEY,
    "content" TEXT NOT NULL,
    "timestamp" INTEGER NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS "autocompleteRanks" (
    "loweredContent" TEXT PRIMARY KEY,
    "content" TEXT NOT NULL,
    "timestamp" INTEGER NOT NULL
  )`,

  `CREATE TABLE IF NOT EXISTS "configurations" (
    "category" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "value" TEXT NOT NULL,
    "lastUpdatedAt" INTEGER NOT NULL DEFAULT CAST(EXTRACT(EPOCH FROM NOW()) AS INTEGER),
    PRIMARY KEY ("category", "name")
  )`,

  `CREATE TABLE IF NOT EXISTS "proxies" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "protocol" TEXT NOT NULL,
    "host" TEXT NOT NULL,
    "port" INTEGER NOT NULL,
    "user" TEXT,
    "password" TEXT,
    "createdAt" INTEGER NOT NULL DEFAULT CAST(EXTRACT(EPOCH FROM NOW()) AS INTEGER)
  )`,
  `CREATE TABLE IF NOT EXISTS "mojangInstances" (
    "name" TEXT PRIMARY KEY,
    "proxyId" INTEGER REFERENCES "proxies"("id") ON DELETE SET NULL,
    "connect" INTEGER NOT NULL DEFAULT 1
  )`,
  `CREATE TABLE IF NOT EXISTS "mojangSessions" (
    "name" TEXT NOT NULL,
    "cacheName" TEXT NOT NULL,
    "value" TEXT NOT NULL,
    "createdAt" INTEGER NOT NULL,
    PRIMARY KEY ("name", "cacheName")
  )`,
  `CREATE TABLE IF NOT EXISTS "mojangProfileSettings" (
    "id" TEXT PRIMARY KEY,
    "playerOnlineStatusEnabled" INTEGER NOT NULL DEFAULT 0,
    "guildAllEnabled" INTEGER NOT NULL DEFAULT 0,
    "guildChatEnabled" INTEGER NOT NULL DEFAULT 0,
    "guildNotificationsEnabled" INTEGER NOT NULL DEFAULT 0,
    "selectedEnglish" INTEGER NOT NULL DEFAULT 0
  )`,

  `CREATE TABLE IF NOT EXISTS "discordLeaderboards" (
    "messageId" TEXT PRIMARY KEY,
    "type" TEXT NOT NULL,
    "channelId" TEXT NOT NULL,
    "guildId" TEXT,
    "updatedAt" INTEGER NOT NULL DEFAULT CAST(EXTRACT(EPOCH FROM NOW()) AS INTEGER),
    "createdAt" INTEGER NOT NULL DEFAULT CAST(EXTRACT(EPOCH FROM NOW()) AS INTEGER)
  )`,
  `CREATE TABLE IF NOT EXISTS "discordTempInteractions" (
    "messageId" TEXT PRIMARY KEY,
    "channelId" TEXT NOT NULL,
    "createdAt" INTEGER NOT NULL DEFAULT CAST(EXTRACT(EPOCH FROM NOW()) AS INTEGER)
  )`,
  `CREATE TABLE IF NOT EXISTS "discordEmojis" (
    "name" TEXT PRIMARY KEY,
    "hash" TEXT NOT NULL,
    "createdAt" INTEGER NOT NULL DEFAULT CAST(EXTRACT(EPOCH FROM NOW()) AS INTEGER)
  )`,

  `CREATE TABLE IF NOT EXISTS "minecraftBots" (
    "uuid" TEXT PRIMARY KEY,
    "updatedAt" INTEGER NOT NULL DEFAULT CAST(EXTRACT(EPOCH FROM NOW()) AS INTEGER),
    "createdAt" INTEGER NOT NULL DEFAULT CAST(EXTRACT(EPOCH FROM NOW()) AS INTEGER)
  )`,

  `CREATE TABLE IF NOT EXISTS "instanceStatusHistory" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "instanceName" TEXT NOT NULL,
    "instanceType" TEXT NOT NULL,
    "fromStatus" TEXT NOT NULL,
    "toStatus" TEXT NOT NULL,
    "createdAt" INTEGER NOT NULL DEFAULT CAST(EXTRACT(EPOCH FROM NOW()) AS INTEGER)
  )`,
  `CREATE TABLE IF NOT EXISTS "instanceMessageHistory" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "instanceName" TEXT NOT NULL,
    "instanceType" TEXT NOT NULL,
    "type" TEXT NOT NULL,
    "value" TEXT,
    "createdAt" INTEGER NOT NULL DEFAULT CAST(EXTRACT(EPOCH FROM NOW()) AS INTEGER)
  )`,

  `CREATE TABLE IF NOT EXISTS "discordInstanceHistoryButton" (
    "messageId" TEXT PRIMARY KEY,
    "channelId" TEXT NOT NULL,
    "instanceName" TEXT NOT NULL,
    "instanceType" TEXT NOT NULL,
    "type" TEXT NOT NULL,
    "startTime" INTEGER NOT NULL,
    "endTime" INTEGER NOT NULL,
    "createdAt" INTEGER NOT NULL DEFAULT CAST(EXTRACT(EPOCH FROM NOW()) AS INTEGER)
  )`,
  `CREATE TABLE IF NOT EXISTS "discordInstanceHistoryLastButton" (
    "messageId" TEXT NOT NULL,
    "channelId" TEXT NOT NULL,
    "instanceName" TEXT NOT NULL,
    "createdAt" INTEGER NOT NULL DEFAULT CAST(EXTRACT(EPOCH FROM NOW()) AS INTEGER),
    PRIMARY KEY ("channelId", "instanceName")
  )`,

  `CREATE TABLE IF NOT EXISTS "inactivity" (
    "uuid" TEXT PRIMARY KEY,
    "discordId" TEXT NOT NULL,
    "reason" TEXT NOT NULL,
    "createdAt" INTEGER NOT NULL,
    "expiresAt" INTEGER NOT NULL
  )`,
  `CREATE INDEX IF NOT EXISTS "inactivityDiscordId" ON "inactivity" ("discordId")`,
  `CREATE INDEX IF NOT EXISTS "inactivityExpiresAt" ON "inactivity" ("expiresAt")`,

  `CREATE TABLE IF NOT EXISTS "rankupPendingReviews" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "bridgeId" TEXT NOT NULL,
    "uuid" TEXT NOT NULL,
    "currentRank" TEXT NOT NULL,
    "proposedRank" TEXT NOT NULL,
    "action" TEXT NOT NULL,
    "reason" TEXT NOT NULL,
    "createdAt" INTEGER NOT NULL DEFAULT CAST(EXTRACT(EPOCH FROM NOW()) AS INTEGER),
    "notifiedAt" INTEGER
  )`,
  `CREATE INDEX IF NOT EXISTS "rankupPendingBridge" ON "rankupPendingReviews" ("bridgeId")`,
  `CREATE UNIQUE INDEX IF NOT EXISTS "rankupPendingUnique" ON "rankupPendingReviews" ("bridgeId", "uuid")`,

  `CREATE TABLE IF NOT EXISTS "rankupHistory" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "bridgeId" TEXT NOT NULL,
    "uuid" TEXT NOT NULL,
    "action" TEXT NOT NULL,
    "fromRank" TEXT NOT NULL,
    "toRank" TEXT NOT NULL,
    "triggeredBy" TEXT NOT NULL,
    "createdAt" INTEGER NOT NULL DEFAULT CAST(EXTRACT(EPOCH FROM NOW()) AS INTEGER)
  )`,
  `CREATE INDEX IF NOT EXISTS "rankupHistoryBridge" ON "rankupHistory" ("bridgeId")`,
  `CREATE INDEX IF NOT EXISTS "rankupHistoryUuid" ON "rankupHistory" ("uuid")`
]

export async function initializeCoreDatabase(
  application: Application,
  sqliteManager: SqliteManager,
  _name: string
): Promise<void> {
  await sqliteManager.awaitReady()

  for (const statement of SchemaStatements) {
    await sqliteManager.execute(statement)
  }

  await migrateFromSqlite(application, sqliteManager)
}

const MigrationTableOrder = [
  'mojang',
  'links',
  'DiscordMessages',
  'MinecraftMessages',
  'DiscordCommands',
  'MinecraftCommands',
  'AllMembers',
  'OnlineMembers',
  'punishments',
  'heatsCommands',
  'heatsCommandsWarnings',
  'autocompleteUsernames',
  'autocompleteRanks',
  'configurations',
  'proxies',
  'mojangInstances',
  'mojangSessions',
  'mojangProfileSettings',
  'discordLeaderboards',
  'discordTempInteractions',
  'discordEmojis',
  'minecraftBots',
  'instanceStatusHistory',
  'instanceMessageHistory',
  'discordInstanceHistoryButton',
  'discordInstanceHistoryLastButton',
  'inactivity',
  'rankupPendingReviews',
  'rankupHistory'
]

const SequenceTables = [
  'AllMembers',
  'OnlineMembers',
  'punishments',
  'heatsCommands',
  'instanceStatusHistory',
  'instanceMessageHistory',
  'proxies',
  'rankupPendingReviews',
  'rankupHistory'
]

const InsertBatchSize = 500

const MigrationColumns: Partial<Record<string, readonly string[]>> = {
  AllMembers: ['id', 'uuid', 'fromTimestamp', 'toTimestamp'],
  OnlineMembers: ['id', 'uuid', 'fromTimestamp', 'toTimestamp']
}

async function migrateFromSqlite(application: Application, sqliteManager: SqliteManager): Promise<void> {
  const sqlitePath = application.getConfigFilePath('users.sqlite')
  if (!fs.existsSync(sqlitePath)) return

  const Database = (await import('better-sqlite3')).default
  const sqliteDb = new Database(sqlitePath, { readonly: true })

  try {
    const tables: Array<{ name: string }> = sqliteDb
      .prepare("SELECT name FROM sqlite_master WHERE type='table' AND name != 'sqlite_sequence'")
      .all() as Array<{ name: string }>
    const tableNames = new Set(tables.map((t) => t.name))

    for (const table of MigrationTableOrder) {
      if (!tableNames.has(table)) continue

      const rows = normalizeRowsForMigration(
        table,
        sqliteDb.prepare(`SELECT * FROM "${table}"`).all() as Record<string, unknown>[]
      )
      if (rows.length === 0) continue

      const columns = getMigrationColumns(table, rows[0])
      if (columns.length === 0) continue

      console.log(`Migrating ${rows.length} rows from SQLite table "${table}"`)

      await sqliteManager.transaction(async (database) => {
        for (const batch of chunkRows(rows, InsertBatchSize)) {
          await insertBatch(database, table, columns, batch)
        }

        if (SequenceTables.includes(table)) {
          const maxIdRow = sqliteDb.prepare(`SELECT MAX(id) as maxId FROM "${table}"`).get() as { maxId: number | null }
          if (maxIdRow.maxId != null) {
            await database.query(`SELECT setval(pg_get_serial_sequence('"${table}"', 'id'), $1)`, [maxIdRow.maxId])
          }
        }
      })
    }

    await sqliteManager.execute(
      'DELETE FROM "proxies" WHERE "id" NOT IN (SELECT "proxyId" FROM "mojangInstances" WHERE "proxyId" IS NOT NULL)'
    )

    sqliteDb.close()

    const backupPath = `${sqlitePath}.migrated-${Date.now()}`
    fs.renameSync(sqlitePath, backupPath)
    console.log(`SQLite migration complete. Old database backed up to: ${backupPath}`)
  } catch (error) {
    sqliteDb.close()
    throw new Error(`Failed to migrate SQLite data to PostgreSQL: ${error}`)
  }
}

function normalizeRowsForMigration(table: string, rows: Record<string, unknown>[]): Record<string, unknown>[] {
  if (table === 'mojangInstances') {
    return dedupeRows(rows, (row) => String(row.name).toLowerCase())
  }

  if (table === 'mojangSessions') {
    return dedupeRows(rows, (row) => `${String(row.name).toLowerCase()}:${String(row.cacheName)}`)
  }

  return rows
}

function dedupeRows(
  rows: Record<string, unknown>[],
  getKey: (row: Record<string, unknown>) => string
): Record<string, unknown>[] {
  const deduped = new Map<string, Record<string, unknown>>()
  for (const row of rows) {
    deduped.set(getKey(row), row)
  }

  return [...deduped.values()]
}

function getMigrationColumns(table: string, row: Record<string, unknown>): string[] {
  const allowedColumns = MigrationColumns[table]
  if (allowedColumns === undefined) return Object.keys(row)
  return allowedColumns.filter((column) => column in row)
}

async function insertBatch(
  database: { query(text: string, values?: readonly unknown[]): Promise<unknown> },
  table: string,
  columns: readonly string[],
  rows: Record<string, unknown>[]
): Promise<void> {
  const valuePlaceholders: string[] = []
  const values: unknown[] = []

  for (const row of rows) {
    const placeholderGroup: string[] = []
    for (const column of columns) {
      values.push(row[column])
      placeholderGroup.push(`$${values.length}`)
    }

    valuePlaceholders.push(`(${placeholderGroup.join(', ')})`)
  }

  await database.query(
    `INSERT INTO "${table}" (${columns.map((column) => `"${column}"`).join(', ')}) VALUES ${valuePlaceholders.join(', ')} ON CONFLICT DO NOTHING`,
    values
  )
}

function chunkRows<T>(rows: T[], size: number): T[][] {
  const chunks: T[][] = []
  for (let index = 0; index < rows.length; index += size) {
    chunks.push(rows.slice(index, index + size))
  }

  return chunks
}
