import type { DatabaseManager } from '../common/database-manager'

const SchemaStatements = [
  `CREATE TABLE IF NOT EXISTS "mojang" (
    "uuid" TEXT PRIMARY KEY,
    "username" TEXT NOT NULL,
    "loweredName" TEXT NOT NULL,
    "createdAt" INTEGER NOT NULL DEFAULT CAST(EXTRACT(EPOCH FROM NOW()) AS INTEGER)
  )`,
  `CREATE UNIQUE INDEX IF NOT EXISTS "mojangLoweredNameUnique" ON "mojang" ("loweredName")`,

  `CREATE TABLE IF NOT EXISTS "links" (
    "uuid" TEXT PRIMARY KEY,
    "discordId" TEXT NOT NULL UNIQUE,
    "createdAt" INTEGER NOT NULL DEFAULT CAST(EXTRACT(EPOCH FROM NOW()) AS INTEGER)
  )`,

  `CREATE TABLE IF NOT EXISTS "DiscordMessages" (
    "timestamp" INTEGER NOT NULL,
    "user" TEXT NOT NULL,
    "count" INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY ("timestamp", "user")
  )`,
  `CREATE TABLE IF NOT EXISTS "MinecraftMessages" (
    "timestamp" INTEGER NOT NULL,
    "user" TEXT NOT NULL,
    "count" INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY ("timestamp", "user")
  )`,
  `CREATE TABLE IF NOT EXISTS "DiscordCommands" (
    "timestamp" INTEGER NOT NULL,
    "user" TEXT NOT NULL,
    "count" INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY ("timestamp", "user")
  )`,
  `CREATE TABLE IF NOT EXISTS "MinecraftCommands" (
    "timestamp" INTEGER NOT NULL,
    "user" TEXT NOT NULL,
    "count" INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY ("timestamp", "user")
  )`,

  `CREATE TABLE IF NOT EXISTS "AllMembers" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "uuid" TEXT NOT NULL,
    "fromTimestamp" INTEGER NOT NULL,
    "toTimestamp" INTEGER NOT NULL,
    CHECK ("fromTimestamp" <= "toTimestamp")
  )`,
  `CREATE TABLE IF NOT EXISTS "OnlineMembers" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "uuid" TEXT NOT NULL,
    "fromTimestamp" INTEGER NOT NULL,
    "toTimestamp" INTEGER NOT NULL,
    CHECK ("fromTimestamp" <= "toTimestamp")
  )`,
  `CREATE INDEX IF NOT EXISTS "allMembersUuidIndex" ON "AllMembers" ("uuid", "fromTimestamp", "toTimestamp")`,
  `CREATE INDEX IF NOT EXISTS "onlineMembersUuidIndex" ON "OnlineMembers" ("uuid", "fromTimestamp", "toTimestamp")`,

  `CREATE TABLE IF NOT EXISTS "guildMemberStates" (
    "instanceName" TEXT NOT NULL,
    "memberUuid" TEXT NOT NULL,
    "memberName" TEXT NOT NULL,
    "rank" TEXT NOT NULL,
    "joinedAt" INTEGER NOT NULL,
    "lastSeenAt" INTEGER NOT NULL,
    "weeklyGexp" INTEGER NOT NULL,
    "dailyGexp" INTEGER NOT NULL,
    "online" INTEGER NOT NULL,
    "updatedAt" INTEGER NOT NULL DEFAULT CAST(EXTRACT(EPOCH FROM NOW()) AS INTEGER),
    PRIMARY KEY ("instanceName", "memberUuid")
  )`,
  `CREATE INDEX IF NOT EXISTS "guildMemberStatesInstanceNameIndex" ON "guildMemberStates" ("instanceName")`,
  `CREATE INDEX IF NOT EXISTS "guildMemberStatesLastSeenIndex" ON "guildMemberStates" ("lastSeenAt")`,

  `CREATE TABLE IF NOT EXISTS "guildMemberEvents" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "instanceName" TEXT NOT NULL,
    "memberUuid" TEXT NOT NULL,
    "memberName" TEXT NOT NULL,
    "eventType" TEXT NOT NULL,
    "rank" TEXT NOT NULL,
    "weeklyGexp" INTEGER NOT NULL,
    "dailyGexp" INTEGER NOT NULL,
    "online" INTEGER NOT NULL,
    "createdAt" INTEGER NOT NULL DEFAULT CAST(EXTRACT(EPOCH FROM NOW()) AS INTEGER)
  )`,
  `CREATE INDEX IF NOT EXISTS "guildMemberEventsInstanceNameIndex" ON "guildMemberEvents" ("instanceName", "createdAt")`,
  `CREATE INDEX IF NOT EXISTS "guildMemberEventsMemberUuidIndex" ON "guildMemberEvents" ("memberUuid", "createdAt")`,

  `CREATE TABLE IF NOT EXISTS "guildMemberDailySnapshots" (
    "snapshotDay" INTEGER NOT NULL,
    "instanceName" TEXT NOT NULL,
    "memberUuid" TEXT NOT NULL,
    "memberName" TEXT NOT NULL,
    "joinedAt" INTEGER NOT NULL,
    "lastSeenAt" INTEGER NOT NULL,
    "weeklyGexp" INTEGER NOT NULL,
    "dailyGexp" INTEGER NOT NULL,
    "online" INTEGER NOT NULL,
    PRIMARY KEY ("snapshotDay", "instanceName", "memberUuid")
  )`,
  `CREATE INDEX IF NOT EXISTS "guildMemberDailySnapshotsInstanceNameIndex" ON "guildMemberDailySnapshots" ("instanceName", "snapshotDay")`,

  `CREATE TABLE IF NOT EXISTS "punishments" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "originInstance" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "type" TEXT NOT NULL,
    "purpose" TEXT NOT NULL,
    "reason" TEXT NOT NULL,
    "createdAt" INTEGER NOT NULL,
    "till" INTEGER NOT NULL
  )`,
  `CREATE INDEX IF NOT EXISTS "punishmentsIndex" ON "punishments" ("originInstance", "userId")`,

  `CREATE TABLE IF NOT EXISTS "heatsCommands" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "originInstance" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "type" TEXT NOT NULL,
    "createdAt" INTEGER NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS "heatsCommandsWarnings" (
    "originInstance" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "type" TEXT NOT NULL,
    "warnedAt" INTEGER NOT NULL,
    PRIMARY KEY ("originInstance", "userId", "type")
  )`,
  `CREATE INDEX IF NOT EXISTS "heatsCommandsIndex" ON "heatsCommands" ("originInstance", "userId")`,

  `CREATE TABLE IF NOT EXISTS "autocompleteUsernames" (
    "loweredContent" TEXT PRIMARY KEY,
    "content" TEXT NOT NULL,
    "timestamp" INTEGER NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS "autocompleteRanks" (
    "loweredContent" TEXT PRIMARY KEY,
    "content" TEXT NOT NULL,
    "timestamp" INTEGER NOT NULL
  )`,

  `CREATE TABLE IF NOT EXISTS "configurations" (
    "category" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "value" TEXT NOT NULL,
    "lastUpdatedAt" INTEGER NOT NULL DEFAULT CAST(EXTRACT(EPOCH FROM NOW()) AS INTEGER),
    PRIMARY KEY ("category", "name")
  )`,

  `CREATE TABLE IF NOT EXISTS "proxies" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "protocol" TEXT NOT NULL,
    "host" TEXT NOT NULL,
    "port" INTEGER NOT NULL,
    "user" TEXT,
    "password" TEXT,
    "createdAt" INTEGER NOT NULL DEFAULT CAST(EXTRACT(EPOCH FROM NOW()) AS INTEGER)
  )`,
  `CREATE TABLE IF NOT EXISTS "mojangInstances" (
    "name" TEXT PRIMARY KEY,
    "proxyId" INTEGER REFERENCES "proxies"("id") ON DELETE SET NULL,
    "connect" INTEGER NOT NULL DEFAULT 1
  )`,
  `CREATE TABLE IF NOT EXISTS "mojangSessions" (
    "name" TEXT NOT NULL,
    "cacheName" TEXT NOT NULL,
    "value" TEXT NOT NULL,
    "createdAt" INTEGER NOT NULL,
    PRIMARY KEY ("name", "cacheName")
  )`,
  `CREATE TABLE IF NOT EXISTS "mojangProfileSettings" (
    "id" TEXT PRIMARY KEY,
    "playerOnlineStatusEnabled" INTEGER NOT NULL DEFAULT 0,
    "guildAllEnabled" INTEGER NOT NULL DEFAULT 0,
    "guildChatEnabled" INTEGER NOT NULL DEFAULT 0,
    "guildNotificationsEnabled" INTEGER NOT NULL DEFAULT 0,
    "selectedEnglish" INTEGER NOT NULL DEFAULT 0
  )`,

  `CREATE TABLE IF NOT EXISTS "discordLeaderboards" (
    "messageId" TEXT PRIMARY KEY,
    "type" TEXT NOT NULL,
    "channelId" TEXT NOT NULL,
    "guildId" TEXT,
    "updatedAt" INTEGER NOT NULL DEFAULT CAST(EXTRACT(EPOCH FROM NOW()) AS INTEGER),
    "createdAt" INTEGER NOT NULL DEFAULT CAST(EXTRACT(EPOCH FROM NOW()) AS INTEGER)
  )`,
  `CREATE TABLE IF NOT EXISTS "discordTempInteractions" (
    "messageId" TEXT PRIMARY KEY,
    "channelId" TEXT NOT NULL,
    "createdAt" INTEGER NOT NULL DEFAULT CAST(EXTRACT(EPOCH FROM NOW()) AS INTEGER)
  )`,
  `CREATE TABLE IF NOT EXISTS "discordEmojis" (
    "name" TEXT PRIMARY KEY,
    "hash" TEXT NOT NULL,
    "createdAt" INTEGER NOT NULL DEFAULT CAST(EXTRACT(EPOCH FROM NOW()) AS INTEGER)
  )`,

  `CREATE TABLE IF NOT EXISTS "minecraftBots" (
    "uuid" TEXT PRIMARY KEY,
    "updatedAt" INTEGER NOT NULL DEFAULT CAST(EXTRACT(EPOCH FROM NOW()) AS INTEGER),
    "createdAt" INTEGER NOT NULL DEFAULT CAST(EXTRACT(EPOCH FROM NOW()) AS INTEGER)
  )`,

  `CREATE TABLE IF NOT EXISTS "instanceStatusHistory" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "instanceName" TEXT NOT NULL,
    "instanceType" TEXT NOT NULL,
    "fromStatus" TEXT NOT NULL,
    "toStatus" TEXT NOT NULL,
    "createdAt" INTEGER NOT NULL DEFAULT CAST(EXTRACT(EPOCH FROM NOW()) AS INTEGER)
  )`,
  `CREATE TABLE IF NOT EXISTS "instanceMessageHistory" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "instanceName" TEXT NOT NULL,
    "instanceType" TEXT NOT NULL,
    "type" TEXT NOT NULL,
    "value" TEXT,
    "createdAt" INTEGER NOT NULL DEFAULT CAST(EXTRACT(EPOCH FROM NOW()) AS INTEGER)
  )`,

  `CREATE TABLE IF NOT EXISTS "discordInstanceHistoryButton" (
    "messageId" TEXT PRIMARY KEY,
    "channelId" TEXT NOT NULL,
    "instanceName" TEXT NOT NULL,
    "instanceType" TEXT NOT NULL,
    "type" TEXT NOT NULL,
    "startTime" INTEGER NOT NULL,
    "endTime" INTEGER NOT NULL,
    "createdAt" INTEGER NOT NULL DEFAULT CAST(EXTRACT(EPOCH FROM NOW()) AS INTEGER)
  )`,
  `CREATE TABLE IF NOT EXISTS "discordInstanceHistoryLastButton" (
    "messageId" TEXT NOT NULL,
    "channelId" TEXT NOT NULL,
    "instanceName" TEXT NOT NULL,
    "createdAt" INTEGER NOT NULL DEFAULT CAST(EXTRACT(EPOCH FROM NOW()) AS INTEGER),
    PRIMARY KEY ("channelId", "instanceName")
  )`,

  `CREATE TABLE IF NOT EXISTS "inactivity" (
    "uuid" TEXT PRIMARY KEY,
    "discordId" TEXT NOT NULL,
    "reason" TEXT NOT NULL,
    "createdAt" INTEGER NOT NULL,
    "expiresAt" INTEGER NOT NULL
  )`,
  `CREATE INDEX IF NOT EXISTS "inactivityDiscordId" ON "inactivity" ("discordId")`,
  `CREATE INDEX IF NOT EXISTS "inactivityExpiresAt" ON "inactivity" ("expiresAt")`,

  `CREATE TABLE IF NOT EXISTS "rankupPendingReviews" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "bridgeId" TEXT NOT NULL,
    "uuid" TEXT NOT NULL,
    "currentRank" TEXT NOT NULL,
    "proposedRank" TEXT NOT NULL,
    "action" TEXT NOT NULL,
    "reason" TEXT NOT NULL,
    "createdAt" INTEGER NOT NULL DEFAULT CAST(EXTRACT(EPOCH FROM NOW()) AS INTEGER),
    "notifiedAt" INTEGER
  )`,
  `CREATE INDEX IF NOT EXISTS "rankupPendingBridge" ON "rankupPendingReviews" ("bridgeId")`,
  `CREATE UNIQUE INDEX IF NOT EXISTS "rankupPendingUnique" ON "rankupPendingReviews" ("bridgeId", "uuid")`,

  `CREATE TABLE IF NOT EXISTS "rankupHistory" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "bridgeId" TEXT NOT NULL,
    "uuid" TEXT NOT NULL,
    "action" TEXT NOT NULL,
    "fromRank" TEXT NOT NULL,
    "toRank" TEXT NOT NULL,
    "triggeredBy" TEXT NOT NULL,
    "createdAt" INTEGER NOT NULL DEFAULT CAST(EXTRACT(EPOCH FROM NOW()) AS INTEGER)
  )`,
  `CREATE INDEX IF NOT EXISTS "rankupHistoryBridge" ON "rankupHistory" ("bridgeId")`,

  `CREATE TABLE IF NOT EXISTS "commandErrors" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "commandName" TEXT NOT NULL,
    "commandMessage" TEXT NOT NULL,
    "username" TEXT NOT NULL,
    "instanceName" TEXT NOT NULL,
    "instanceType" TEXT NOT NULL,
    "bridgeId" TEXT,
    "errorType" TEXT,
    "errorMessage" TEXT,
    "errorStack" TEXT,
    "createdAt" INTEGER NOT NULL DEFAULT CAST(EXTRACT(EPOCH FROM NOW()) AS INTEGER)
  )`,
  `CREATE INDEX IF NOT EXISTS "commandErrorsCommandName" ON "commandErrors" ("commandName")`,
  `CREATE INDEX IF NOT EXISTS "commandErrorsCreatedAt" ON "commandErrors" ("createdAt")`,

  `CREATE TABLE IF NOT EXISTS "statMonitors" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ownerId" TEXT NOT NULL,
    "playerUuid" TEXT NOT NULL,
    "playerName" TEXT NOT NULL,
    "game" TEXT NOT NULL,
    "stat" TEXT NOT NULL,
    "lastValue" DOUBLE PRECISION,
    "threshold" DOUBLE PRECISION,
    "bridgeId" TEXT,
    "createdAt" INTEGER NOT NULL DEFAULT CAST(EXTRACT(EPOCH FROM NOW()) AS INTEGER),
    UNIQUE ("ownerId", "playerUuid", "game", "stat")
  )`,
  `CREATE INDEX IF NOT EXISTS "statMonitorsOwnerIndex" ON "statMonitors" ("ownerId")`,
  `CREATE INDEX IF NOT EXISTS "statMonitorsPlayerIndex" ON "statMonitors" ("playerUuid")`
]

/**
 * Applied after the main schema loop so databases that were initialized before
 * disconnectLogs existed still get the table on upgrade (idempotent).
 */
const DisconnectLogsSchemaStatements = [
  `CREATE TABLE IF NOT EXISTS "disconnectLogs" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "instanceName" TEXT NOT NULL,
    "eventType" TEXT NOT NULL,
    "reason" TEXT NOT NULL,
    "createdAt" INTEGER NOT NULL DEFAULT CAST(EXTRACT(EPOCH FROM NOW()) AS INTEGER)
  )`,
  `CREATE INDEX IF NOT EXISTS "disconnectLogsInstanceName" ON "disconnectLogs" ("instanceName")`,
  `CREATE INDEX IF NOT EXISTS "disconnectLogsCreatedAt" ON "disconnectLogs" ("createdAt")`
] as const

export async function initializeCoreDatabase(databaseManager: DatabaseManager): Promise<void> {
  await databaseManager.awaitReady()

  await databaseManager.runMigrations()

  await syncSequences(databaseManager)
}

async function syncSequences(databaseManager: DatabaseManager): Promise<void> {
  const tables = [
    'AllMembers',
    'OnlineMembers',
    'guildMemberStates',
    'guildMemberEvents',
    'guildMemberDailySnapshots',
    'punishments',
    'heatsCommands',
    'proxies',
    'instanceStatusHistory',
    'instanceMessageHistory',
    'rankupPendingReviews',
    'rankupHistory',
    'disconnectLogs',
    'commandErrors',
    'statMonitors'
  ]

  for (const table of tables) {
    try {
      // This query works for both SERIAL and IDENTITY columns in PostgreSQL.
      // We use coalesce to handle empty tables, resetting the sequence to 1.
      await databaseManager.execute(`
        SELECT setval(
          pg_get_serial_sequence('"${table}"', 'id'),
          COALESCE(MAX(id), 0) + 1,
          false
        ) FROM "${table}"
      `)
    } catch {
      // In-memory databases or non-Postgres environments might not support this.
      // We ignore the error as it's a non-critical optimization/fixup.
    }
  }
}
