/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const GeneralConfig = t.iface([], {
  "hypixelApiKey": "string",
  "urchinApiKey": t.opt("string"),
  "openrouterApiKey": t.opt("string"),
  "openrouterModel": t.opt("string"),
});

export const StaticDiscordConfig = t.iface([], {
  "key": "string",
  "adminIds": t.array("string"),
});

export const PrometheusConfig = t.iface([], {
  "enabled": "boolean",
  "port": "number",
  "prefix": "string",
  "exportPerMember": t.opt("boolean"),
  "token": t.opt("string"),
});

export const DatabaseConfig = t.iface([], {
  "url": t.opt("string"),
  "ssl": t.opt("boolean"),
  "maxConnections": t.opt("number"),
});

export const WebConfig = t.iface([], {
  "enabled": "boolean",
  "port": "number",
  "signingSecret": t.opt("string"),
  "minecraftInstance": t.opt("string"),
});

export const StatsChannelConfig = t.iface([], {
  "id": "string",
  "name": "string",
});

export const StatsChannelsConfig = t.iface([], {
  "enabled": "boolean",
  "updateIntervalMinutes": "number",
  "channels": t.array("StatsChannelConfig"),
  "guildName": t.opt("string"),
  "minecraftInstance": t.opt("string"),
});

export const VerificationRoleConfig = t.iface([], {
  "enabled": "boolean",
  "roleId": "string",
});

export const LevelRole = t.iface([], {
  "type": "string",
  "requirement": t.union("number", "string"),
  "roleId": "string",
});

export const VerificationConfig = t.iface([], {
  "nickname": "string",
  "roles": t.iface([], {
    "verified": "VerificationRoleConfig",
    "guildMember": "VerificationRoleConfig",
    "custom": t.array("LevelRole"),
  }),
  "autoRoleUpdater": t.iface([], {
    "enabled": "boolean",
    "interval": "number",
  }),
});

export const GuildRequirementsThresholds = t.iface([], {
  "bedwarsStars": "number",
  "bedwarsFKDR": "number",
  "skywarsStars": "number",
  "skywarsKDR": "number",
  "duelsWins": "number",
  "duelsWLR": "number",
  "skyblockLevel": "number",
});

export const GuildRequirementsConfig = t.iface([], {
  "enabled": "boolean",
  "requirements": "GuildRequirementsThresholds",
  "autoAccept": t.opt("boolean"),
});

export const InterviewConfig = t.iface([], {
  "enabled": t.opt("boolean"),
  "question": t.opt("string"),
  "timeoutMs": t.opt("number"),
});

export const InactivityConfig = t.iface([], {
  "enabled": "boolean",
  "maxDays": "number",
  "channelIds": t.array("string"),
});

export const TournamentConfig = t.iface([], {
  "categoryId": "string",
  "roundDeadlineDays": "number",
  "defaultGameMode": t.union(t.lit('bridge'), t.lit('bedwars')),
  "bestOf": "number",
  "staffRoleIds": t.opt(t.array("string")),
  "reminderHours": t.opt(t.array("number")),
});

export const LunarClientConfig = t.iface([], {
  "enabled": t.opt("boolean"),
  "minecraftInstance": t.opt("string"),
  "cacheSeconds": t.opt("number"),
});

export const ApplicationConfig = t.iface([], {
  "version": t.lit(2),
  "general": "GeneralConfig",
  "discord": "StaticDiscordConfig",
  "prometheus": "PrometheusConfig",
  "database": t.opt("DatabaseConfig"),
  "web": t.opt("WebConfig"),
  "statsChannels": t.opt("StatsChannelsConfig"),
  "verification": t.opt("VerificationConfig"),
  "guildRequirements": t.opt("GuildRequirementsConfig"),
  "inactivity": t.opt("InactivityConfig"),
  "tournament": t.opt("TournamentConfig"),
  "lunarClient": t.opt("LunarClientConfig"),
});

const exportedTypeSuite: t.ITypeSuite = {
  GeneralConfig,
  StaticDiscordConfig,
  PrometheusConfig,
  DatabaseConfig,
  WebConfig,
  StatsChannelConfig,
  StatsChannelsConfig,
  VerificationRoleConfig,
  LevelRole,
  VerificationConfig,
  GuildRequirementsThresholds,
  GuildRequirementsConfig,
  InterviewConfig,
  InactivityConfig,
  TournamentConfig,
  LunarClientConfig,
  ApplicationConfig,
};
export default exportedTypeSuite;
