import type Database from 'better-sqlite3'
import type { Logger } from 'log4js'
import { Pool, types, type Pool as PgPool } from 'pg'

import type Application from '../application.js'

types.setTypeParser(20, (value) => Number.parseInt(value, 10))

const CurrentEpochSql = 'extract(epoch from now())::bigint'
const MetadataTable = '_postgres_mirror_state'
const SeededMetadataKey = 'seeded_from_sqlite'

export interface MirroredTableDefinition {
  readonly name: string
  readonly columns: readonly string[]
  readonly createStatements: readonly string[]
  readonly orderBy?: readonly string[]
}

export const MirroredTables: readonly MirroredTableDefinition[] = [
  {
    name: 'mojang',
    columns: ['uuid', 'username', 'loweredName', 'createdAt'],
    orderBy: ['uuid'],
    createStatements: [
      `CREATE TABLE IF NOT EXISTS "mojang" (
        "uuid" text PRIMARY KEY,
        "username" text NOT NULL UNIQUE,
        "loweredName" text NOT NULL UNIQUE,
        "createdAt" bigint NOT NULL DEFAULT ${CurrentEpochSql}
      )`
    ]
  },
  {
    name: 'links',
    columns: ['uuid', 'discordId', 'createdAt'],
    orderBy: ['uuid', 'discordId'],
    createStatements: [
      `CREATE TABLE IF NOT EXISTS "links" (
        "uuid" text NOT NULL,
        "discordId" text NOT NULL,
        "createdAt" bigint NOT NULL DEFAULT ${CurrentEpochSql},
        PRIMARY KEY ("uuid", "discordId")
      )`
    ]
  },
  {
    name: 'DiscordMessages',
    columns: ['timestamp', 'user', 'count'],
    orderBy: ['timestamp', 'user'],
    createStatements: [
      `CREATE TABLE IF NOT EXISTS "DiscordMessages" (
        "timestamp" bigint NOT NULL,
        "user" text NOT NULL,
        "count" integer NOT NULL DEFAULT 0,
        PRIMARY KEY ("timestamp", "user")
      )`
    ]
  },
  {
    name: 'MinecraftMessages',
    columns: ['timestamp', 'user', 'count'],
    orderBy: ['timestamp', 'user'],
    createStatements: [
      `CREATE TABLE IF NOT EXISTS "MinecraftMessages" (
        "timestamp" bigint NOT NULL,
        "user" text NOT NULL,
        "count" integer NOT NULL DEFAULT 0,
        PRIMARY KEY ("timestamp", "user")
      )`
    ]
  },
  {
    name: 'DiscordCommands',
    columns: ['timestamp', 'user', 'count'],
    orderBy: ['timestamp', 'user'],
    createStatements: [
      `CREATE TABLE IF NOT EXISTS "DiscordCommands" (
        "timestamp" bigint NOT NULL,
        "user" text NOT NULL,
        "count" integer NOT NULL DEFAULT 0,
        PRIMARY KEY ("timestamp", "user")
      )`
    ]
  },
  {
    name: 'MinecraftCommands',
    columns: ['timestamp', 'user', 'count'],
    orderBy: ['timestamp', 'user'],
    createStatements: [
      `CREATE TABLE IF NOT EXISTS "MinecraftCommands" (
        "timestamp" bigint NOT NULL,
        "user" text NOT NULL,
        "count" integer NOT NULL DEFAULT 0,
        PRIMARY KEY ("timestamp", "user")
      )`
    ]
  },
  {
    name: 'AllMembers',
    columns: ['id', 'uuid', 'fromTimestamp', 'toTimestamp'],
    orderBy: ['id'],
    createStatements: [
      `CREATE TABLE IF NOT EXISTS "AllMembers" (
        "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "uuid" text NOT NULL,
        "fromDate" date GENERATED ALWAYS AS (to_timestamp("fromTimestamp")::date) STORED,
        "fromTimestamp" bigint NOT NULL,
        "toDate" date GENERATED ALWAYS AS (to_timestamp("toTimestamp")::date) STORED,
        "toTimestamp" bigint NOT NULL,
        CONSTRAINT "AllMembers_timeRange" CHECK ("fromTimestamp" <= "toTimestamp")
      )`,
      'CREATE INDEX IF NOT EXISTS "allMembersAppend" ON "AllMembers" ("uuid", "fromDate", "toDate")'
    ]
  },
  {
    name: 'OnlineMembers',
    columns: ['id', 'uuid', 'fromTimestamp', 'toTimestamp'],
    orderBy: ['id'],
    createStatements: [
      `CREATE TABLE IF NOT EXISTS "OnlineMembers" (
        "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "uuid" text NOT NULL,
        "fromDate" date GENERATED ALWAYS AS (to_timestamp("fromTimestamp")::date) STORED,
        "fromTimestamp" bigint NOT NULL,
        "toDate" date GENERATED ALWAYS AS (to_timestamp("toTimestamp")::date) STORED,
        "toTimestamp" bigint NOT NULL,
        CONSTRAINT "OnlineMembers_timeRange" CHECK ("fromTimestamp" <= "toTimestamp")
      )`,
      'CREATE INDEX IF NOT EXISTS "onlineMembersAppend" ON "OnlineMembers" ("uuid", "fromDate", "toDate")'
    ]
  },
  {
    name: 'punishments',
    columns: ['id', 'originInstance', 'userId', 'type', 'purpose', 'reason', 'createdAt', 'till'],
    orderBy: ['id'],
    createStatements: [
      `CREATE TABLE IF NOT EXISTS "punishments" (
        "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "originInstance" text NOT NULL,
        "userId" text NOT NULL,
        "type" text NOT NULL,
        "purpose" text NOT NULL,
        "reason" text NOT NULL,
        "createdAt" bigint NOT NULL,
        "till" bigint NOT NULL
      )`,
      'CREATE INDEX IF NOT EXISTS "punishmentsIndex" ON "punishments" ("originInstance", "userId")'
    ]
  },
  {
    name: 'heatsCommands',
    columns: ['id', 'originInstance', 'userId', 'type', 'createdAt'],
    orderBy: ['id'],
    createStatements: [
      `CREATE TABLE IF NOT EXISTS "heatsCommands" (
        "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "originInstance" text NOT NULL,
        "userId" text NOT NULL,
        "type" text NOT NULL,
        "createdAt" bigint NOT NULL
      )`,
      'CREATE INDEX IF NOT EXISTS "heatsCommandsIndex" ON "heatsCommands" ("originInstance", "userId")'
    ]
  },
  {
    name: 'heatsCommandsWarnings',
    columns: ['originInstance', 'userId', 'type', 'warnedAt'],
    orderBy: ['originInstance', 'userId', 'type'],
    createStatements: [
      `CREATE TABLE IF NOT EXISTS "heatsCommandsWarnings" (
        "originInstance" text NOT NULL,
        "userId" text NOT NULL,
        "type" text NOT NULL,
        "warnedAt" bigint NOT NULL,
        PRIMARY KEY ("originInstance", "userId", "type")
      )`
    ]
  },
  {
    name: 'autocompleteUsernames',
    columns: ['loweredContent', 'content', 'timestamp'],
    orderBy: ['loweredContent'],
    createStatements: [
      `CREATE TABLE IF NOT EXISTS "autocompleteUsernames" (
        "loweredContent" text PRIMARY KEY,
        "content" text NOT NULL,
        "timestamp" bigint NOT NULL
      )`
    ]
  },
  {
    name: 'autocompleteRanks',
    columns: ['loweredContent', 'content', 'timestamp'],
    orderBy: ['loweredContent'],
    createStatements: [
      `CREATE TABLE IF NOT EXISTS "autocompleteRanks" (
        "loweredContent" text PRIMARY KEY,
        "content" text NOT NULL,
        "timestamp" bigint NOT NULL
      )`
    ]
  },
  {
    name: 'configurations',
    columns: ['category', 'name', 'value', 'lastUpdatedAt'],
    orderBy: ['category', 'name'],
    createStatements: [
      `CREATE TABLE IF NOT EXISTS "configurations" (
        "category" text NOT NULL,
        "name" text NOT NULL,
        "value" text NOT NULL,
        "lastUpdatedAt" bigint NOT NULL DEFAULT ${CurrentEpochSql},
        PRIMARY KEY ("category", "name")
      )`
    ]
  },
  {
    name: 'proxies',
    columns: ['id', 'protocol', 'host', 'port', 'user', 'password', 'createdAt'],
    orderBy: ['id'],
    createStatements: [
      `CREATE TABLE IF NOT EXISTS "proxies" (
        "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "protocol" text NOT NULL,
        "host" text NOT NULL,
        "port" integer NOT NULL,
        "user" text DEFAULT NULL,
        "password" text DEFAULT NULL,
        "createdAt" bigint NOT NULL DEFAULT ${CurrentEpochSql}
      )`
    ]
  },
  {
    name: 'mojangInstances',
    columns: ['name', 'proxyId', 'connect'],
    orderBy: ['name'],
    createStatements: [
      `CREATE TABLE IF NOT EXISTS "mojangInstances" (
        "name" text PRIMARY KEY,
        "proxyId" bigint REFERENCES "proxies" ("id") ON DELETE SET NULL,
        "connect" integer NOT NULL DEFAULT 1
      )`
    ]
  },
  {
    name: 'mojangSessions',
    columns: ['name', 'cacheName', 'value', 'createdAt'],
    orderBy: ['name', 'cacheName'],
    createStatements: [
      `CREATE TABLE IF NOT EXISTS "mojangSessions" (
        "name" text NOT NULL REFERENCES "mojangInstances" ("name") ON DELETE CASCADE,
        "cacheName" text NOT NULL,
        "value" text NOT NULL,
        "createdAt" bigint NOT NULL,
        PRIMARY KEY ("name", "cacheName")
      )`
    ]
  },
  {
    name: 'mojangProfileSettings',
    columns: [
      'id',
      'playerOnlineStatusEnabled',
      'guildAllEnabled',
      'guildChatEnabled',
      'guildNotificationsEnabled',
      'selectedEnglish'
    ],
    orderBy: ['id'],
    createStatements: [
      `CREATE TABLE IF NOT EXISTS "mojangProfileSettings" (
        "id" text PRIMARY KEY,
        "playerOnlineStatusEnabled" integer NOT NULL DEFAULT 0,
        "guildAllEnabled" integer NOT NULL DEFAULT 0,
        "guildChatEnabled" integer NOT NULL DEFAULT 0,
        "guildNotificationsEnabled" integer NOT NULL DEFAULT 0,
        "selectedEnglish" integer NOT NULL DEFAULT 0
      )`
    ]
  },
  {
    name: 'discordLeaderboards',
    columns: ['messageId', 'type', 'channelId', 'guildId', 'updatedAt', 'createdAt'],
    orderBy: ['messageId'],
    createStatements: [
      `CREATE TABLE IF NOT EXISTS "discordLeaderboards" (
        "messageId" text PRIMARY KEY,
        "type" text NOT NULL,
        "channelId" text NOT NULL,
        "guildId" text DEFAULT NULL,
        "updatedAt" bigint NOT NULL DEFAULT ${CurrentEpochSql},
        "createdAt" bigint NOT NULL DEFAULT ${CurrentEpochSql}
      )`
    ]
  },
  {
    name: 'discordTempInteractions',
    columns: ['messageId', 'channelId', 'createdAt'],
    orderBy: ['messageId'],
    createStatements: [
      `CREATE TABLE IF NOT EXISTS "discordTempInteractions" (
        "messageId" text PRIMARY KEY,
        "channelId" text NOT NULL,
        "createdAt" bigint NOT NULL DEFAULT ${CurrentEpochSql}
      )`
    ]
  },
  {
    name: 'discordEmojis',
    columns: ['name', 'hash', 'createdAt'],
    orderBy: ['name'],
    createStatements: [
      `CREATE TABLE IF NOT EXISTS "discordEmojis" (
        "name" text PRIMARY KEY,
        "hash" text NOT NULL,
        "createdAt" bigint NOT NULL DEFAULT ${CurrentEpochSql}
      )`
    ]
  },
  {
    name: 'minecraftBots',
    columns: ['uuid', 'updatedAt', 'createdAt'],
    orderBy: ['uuid'],
    createStatements: [
      `CREATE TABLE IF NOT EXISTS "minecraftBots" (
        "uuid" text PRIMARY KEY,
        "updatedAt" bigint NOT NULL DEFAULT ${CurrentEpochSql},
        "createdAt" bigint NOT NULL DEFAULT ${CurrentEpochSql}
      )`
    ]
  },
  {
    name: 'instanceStatusHistory',
    columns: ['id', 'instanceName', 'instanceType', 'fromStatus', 'toStatus', 'createdAt'],
    orderBy: ['id'],
    createStatements: [
      `CREATE TABLE IF NOT EXISTS "instanceStatusHistory" (
        "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "instanceName" text NOT NULL,
        "instanceType" text NOT NULL,
        "fromStatus" text NOT NULL,
        "toStatus" text NOT NULL,
        "createdAt" bigint NOT NULL DEFAULT ${CurrentEpochSql}
      )`
    ]
  },
  {
    name: 'instanceMessageHistory',
    columns: ['id', 'instanceName', 'instanceType', 'type', 'value', 'createdAt'],
    orderBy: ['id'],
    createStatements: [
      `CREATE TABLE IF NOT EXISTS "instanceMessageHistory" (
        "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "instanceName" text NOT NULL,
        "instanceType" text NOT NULL,
        "type" text NOT NULL,
        "value" text DEFAULT NULL,
        "createdAt" bigint NOT NULL DEFAULT ${CurrentEpochSql}
      )`
    ]
  },
  {
    name: 'discordInstanceHistoryButton',
    columns: ['messageId', 'channelId', 'instanceName', 'instanceType', 'type', 'startTime', 'endTime'],
    orderBy: ['channelId', 'instanceName', 'endTime', 'messageId'],
    createStatements: [
      `CREATE TABLE IF NOT EXISTS "discordInstanceHistoryButton" (
        "messageId" text NOT NULL,
        "channelId" text NOT NULL,
        "instanceName" text NOT NULL,
        "instanceType" text NOT NULL,
        "type" text NOT NULL,
        "startTime" bigint NOT NULL DEFAULT ${CurrentEpochSql},
        "endTime" bigint NOT NULL DEFAULT ${CurrentEpochSql}
      )`
    ]
  },
  {
    name: 'discordInstanceHistoryLastButton',
    columns: ['messageId', 'channelId', 'instanceName', 'createdAt'],
    orderBy: ['channelId', 'instanceName'],
    createStatements: [
      `CREATE TABLE IF NOT EXISTS "discordInstanceHistoryLastButton" (
        "messageId" text NOT NULL,
        "channelId" text NOT NULL,
        "instanceName" text NOT NULL,
        "createdAt" bigint NOT NULL DEFAULT ${CurrentEpochSql},
        PRIMARY KEY ("channelId", "instanceName")
      )`
    ]
  },
  {
    name: 'inactivity',
    columns: ['uuid', 'discordId', 'reason', 'createdAt', 'expiresAt'],
    orderBy: ['uuid'],
    createStatements: [
      `CREATE TABLE IF NOT EXISTS "inactivity" (
        "uuid" text PRIMARY KEY,
        "discordId" text NOT NULL,
        "reason" text NOT NULL,
        "createdAt" bigint NOT NULL,
        "expiresAt" bigint NOT NULL
      )`,
      'CREATE INDEX IF NOT EXISTS "inactivityDiscordId" ON "inactivity" ("discordId")',
      'CREATE INDEX IF NOT EXISTS "inactivityExpiresAt" ON "inactivity" ("expiresAt")'
    ]
  },
  {
    name: 'rankupPendingReviews',
    columns: ['id', 'bridgeId', 'uuid', 'currentRank', 'proposedRank', 'action', 'reason', 'createdAt', 'notifiedAt'],
    orderBy: ['id'],
    createStatements: [
      `CREATE TABLE IF NOT EXISTS "rankupPendingReviews" (
        "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "bridgeId" text NOT NULL,
        "uuid" text NOT NULL,
        "currentRank" text NOT NULL,
        "proposedRank" text NOT NULL,
        "action" text NOT NULL,
        "reason" text NOT NULL,
        "createdAt" bigint NOT NULL DEFAULT ${CurrentEpochSql},
        "notifiedAt" bigint DEFAULT NULL
      )`,
      'CREATE INDEX IF NOT EXISTS "rankupPendingBridge" ON "rankupPendingReviews" ("bridgeId")',
      'CREATE UNIQUE INDEX IF NOT EXISTS "rankupPendingUnique" ON "rankupPendingReviews" ("bridgeId", "uuid")'
    ]
  },
  {
    name: 'rankupHistory',
    columns: ['id', 'bridgeId', 'uuid', 'action', 'fromRank', 'toRank', 'triggeredBy', 'createdAt'],
    orderBy: ['id'],
    createStatements: [
      `CREATE TABLE IF NOT EXISTS "rankupHistory" (
        "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "bridgeId" text NOT NULL,
        "uuid" text NOT NULL,
        "action" text NOT NULL,
        "fromRank" text NOT NULL,
        "toRank" text NOT NULL,
        "triggeredBy" text NOT NULL,
        "createdAt" bigint NOT NULL DEFAULT ${CurrentEpochSql}
      )`,
      'CREATE INDEX IF NOT EXISTS "rankupHistoryBridge" ON "rankupHistory" ("bridgeId")',
      'CREATE INDEX IF NOT EXISTS "rankupHistoryUuid" ON "rankupHistory" ("uuid")'
    ]
  }
] as const

const ReplaceConflictTargets = new Map<string, readonly string[]>([
  ['autocompleteUsernames', ['loweredContent']],
  ['autocompleteRanks', ['loweredContent']],
  ['configurations', ['category', 'name']],
  ['mojangSessions', ['name', 'cacheName']],
  ['mojangProfileSettings', ['id']],
  ['heatsCommandsWarnings', ['originInstance', 'userId', 'type']],
  ['inactivity', ['uuid']],
  ['discordInstanceHistoryLastButton', ['channelId', 'instanceName']],
  ['discordLeaderboards', ['messageId']],
  ['discordTempInteractions', ['messageId']],
  ['discordEmojis', ['name']]
])

const ReplaceDefaultColumns = new Map<string, readonly string[]>([
  ['discordLeaderboards', ['updatedAt', 'createdAt']],
  ['discordEmojis', ['createdAt']]
])

const TargetlessUpserts = new Map<string, readonly string[]>([
  ['DiscordMessages', ['timestamp', 'user']],
  ['MinecraftMessages', ['timestamp', 'user']],
  ['DiscordCommands', ['timestamp', 'user']],
  ['MinecraftCommands', ['timestamp', 'user']]
])

interface CapturedWrite {
  readonly sql: string
  readonly args: unknown[]
}

export class PostgresMirror {
  private readonly pool: Pool
  private writeQueue = Promise.resolve()
  private readonly captureStack: CapturedWrite[][] = []
  private attached = false

  public constructor(
    private readonly application: Application,
    private readonly logger: Logger,
    connectionString: string
  ) {
    this.pool = new Pool({
      connectionString,
      ssl: { rejectUnauthorized: false }
    })

    this.application.addShutdownListener(async () => {
      await this.close()
    })
  }

  public static createFromEnvironment(application: Application, logger: Logger): PostgresMirror | undefined {
    const connectionString = process.env.DATABASE_URL
    if (connectionString === undefined || connectionString.length === 0) return undefined
    return new PostgresMirror(application, logger, connectionString)
  }

  public async initialize(sqliteDatabase: Database.Database): Promise<void> {
    await this.ensureSchema()

    if (await this.hasSeededSnapshot()) {
      await this.hydrateSqlite(sqliteDatabase)
      this.logger.info('Loaded persisted data from Postgres into local SQLite cache')
    } else {
      this.logger.warn(
        'DATABASE_URL is set, but Postgres has not been seeded yet. Continuing with SQLite until migration runs.'
      )
    }

    this.attach(sqliteDatabase)
  }

  public async close(): Promise<void> {
    await this.writeQueue.catch(() => undefined)
    await this.pool.end()
  }

  public async markSeeded(): Promise<void> {
    await markPostgresMirrorSeeded(this.pool)
  }

  private async ensureSchema(): Promise<void> {
    await ensurePostgresMirrorSchema(this.pool)
  }

  private async hasSeededSnapshot(): Promise<boolean> {
    const result = await this.pool.query<{ value: string }>(
      `SELECT value FROM ${MetadataTable} WHERE key = $1 LIMIT 1`,
      [SeededMetadataKey]
    )
    return result.rows[0]?.value === '1'
  }

  private async hydrateSqlite(sqliteDatabase: Database.Database): Promise<void> {
    const tableRows = new Map<string, Record<string, unknown>[]>()

    for (const table of MirroredTables) {
      const selectSql = `SELECT ${quoteColumns(table.columns)} FROM ${quoteIdentifier(table.name)}${renderOrderBy(table.orderBy)}`
      const result = await this.pool.query<Record<string, unknown>>(selectSql)
      tableRows.set(table.name, result.rows)
    }

    const transaction = sqliteDatabase.transaction(() => {
      for (const table of MirroredTables.toReversed()) {
        sqliteDatabase.prepare(`DELETE FROM ${quoteIdentifier(table.name)}`).run()
      }

      for (const table of MirroredTables) {
        const rows = tableRows.get(table.name) ?? []
        if (rows.length === 0) continue

        const placeholders = table.columns.map(() => '?').join(', ')
        const insert = sqliteDatabase.prepare(
          `INSERT INTO ${quoteIdentifier(table.name)} (${quoteColumns(table.columns)}) VALUES (${placeholders})`
        )

        for (const row of rows) {
          const values = table.columns.map((column) => row[column] ?? null)
          insert.run(...values)
        }
      }
    })

    transaction()
  }

  private attach(sqliteDatabase: Database.Database): void {
    if (this.attached) return
    this.attached = true

    const originalPrepare = sqliteDatabase.prepare.bind(sqliteDatabase)
    const originalTransaction = sqliteDatabase.transaction.bind(sqliteDatabase)

    ;(sqliteDatabase as any).prepare = (sql: string) => {
      const statement = originalPrepare(sql)
      return this.wrapStatement(statement, sql)
    }
    ;(sqliteDatabase as any).transaction = (callback: (...parameters: any[]) => unknown) => {
      const sqliteTransaction = originalTransaction((...parameters: any[]) => {
        this.captureStack.push([])

        try {
          const result = callback(...parameters)
          const operations = this.captureStack.pop() ?? []
          if (this.captureStack.length > 0) {
            this.captureStack[this.captureStack.length - 1].push(...operations)
          } else if (operations.length > 0) {
            this.enqueueWrites(operations)
          }

          return result
        } catch (error) {
          this.captureStack.pop()
          throw error
        }
      })

      return wrapTransactionRunner(sqliteTransaction)
    }
  }

  private wrapStatement(statement: Database.Statement, sql: string): Database.Statement {
    const normalizedSql = sql.trim()
    const mirror = this

    return new Proxy(statement as object, {
      get(target, property, receiver) {
        if (property === 'run') {
          return (...parameters: any[]) => {
            const result = (statement.run as any)(...parameters)
            if (isMutatingStatement(normalizedSql)) {
              mirror.recordWrite(normalizedSql, parameters)
            }

            return result
          }
        }

        if (property === 'pluck') {
          return (...parameters: any[]) => {
            ;(statement.pluck as any)(...parameters)
            return receiver
          }
        }

        const value = Reflect.get(target, property, receiver)
        return typeof value === 'function' ? value.bind(target) : value
      }
    }) as Database.Statement
  }

  private recordWrite(sql: string, rawParameters: unknown[]): void {
    const parameters = normalizeParameters(rawParameters)
    const operation: CapturedWrite = { sql, args: parameters }

    if (this.captureStack.length > 0) {
      this.captureStack[this.captureStack.length - 1].push(operation)
      return
    }

    this.enqueueWrites([operation])
  }

  private enqueueWrites(operations: readonly CapturedWrite[]): void {
    this.writeQueue = this.writeQueue
      .then(async () => {
        if (operations.length === 0) return

        const client = await this.pool.connect()
        try {
          await client.query('BEGIN')
          for (const operation of operations) {
            const translated = translateWriteStatement(operation.sql, operation.args)
            await client.query(translated.sql, translated.parameters)
          }
          await client.query('COMMIT')
        } catch (error) {
          await client.query('ROLLBACK').catch(() => undefined)
          this.logger.error(`Failed mirroring SQLite write to Postgres: ${error}`)
        } finally {
          client.release()
        }
      })
      .catch((error: unknown) => {
        this.logger.error(`Postgres mirror queue failed: ${error}`)
      })
  }
}

export async function ensurePostgresMirrorSchema(pool: PgPool): Promise<void> {
  await pool.query(
    `CREATE TABLE IF NOT EXISTS ${MetadataTable} (
      key text PRIMARY KEY,
      value text NOT NULL,
      updated_at bigint NOT NULL DEFAULT ${CurrentEpochSql}
    )`
  )

  for (const table of MirroredTables) {
    for (const statement of table.createStatements) {
      await pool.query(statement)
    }
  }
}

export async function markPostgresMirrorSeeded(pool: PgPool): Promise<void> {
  await pool.query(
    `INSERT INTO ${MetadataTable} (key, value, updated_at)
     VALUES ($1, $2, ${CurrentEpochSql})
     ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value, updated_at = EXCLUDED.updated_at`,
    [SeededMetadataKey, '1']
  )
}

function wrapTransactionRunner(transactionRunner: any): any {
  const wrapped: any = (...parameters: any[]) => transactionRunner(...parameters)

  for (const mode of ['deferred', 'immediate', 'exclusive'] as const) {
    if (typeof transactionRunner[mode] === 'function') {
      wrapped[mode] = (...parameters: any[]) => transactionRunner[mode](...parameters)
    }
  }

  return wrapped
}

function isMutatingStatement(sql: string): boolean {
  return /^(INSERT|UPDATE|DELETE)/i.test(sql)
}

function normalizeParameters(rawParameters: unknown[]): unknown[] {
  if (rawParameters.length === 1) {
    const first = rawParameters[0]
    if (Array.isArray(first)) return [...first]
    if (isPlainObject(first)) return [first]
  }

  return [...rawParameters]
}

function isPlainObject(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value)
}

function translateWriteStatement(sql: string, parameters: readonly unknown[]): { sql: string; parameters: unknown[] } {
  let translatedSql = sql.trim().replaceAll(/unixepoch\(\)/gi, CurrentEpochSql)
  let translatedParameters = [...parameters]

  translatedSql = rewriteInsertOrReplace(translatedSql)
  translatedSql = rewriteTargetlessUpsert(translatedSql)
  translatedSql = rewriteMojangReplace(translatedSql)

  const bound = bindParameters(translatedSql, translatedParameters)
  return bound
}

function rewriteInsertOrReplace(sql: string): string {
  const match = /^INSERT OR REPLACE INTO\s+"?([A-Za-z0-9_]+)"?\s*\(([^)]+)\)\s*VALUES\s*\(([^)]+)\)$/i.exec(sql)
  if (match === null) return sql

  const [, tableName, rawColumns, rawValues] = match
  if (tableName === 'mojang') return sql

  const conflictColumns = ReplaceConflictTargets.get(tableName)
  if (conflictColumns === undefined) {
    throw new Error(`No Postgres REPLACE mapping configured for table '${tableName}'`)
  }

  const columns = splitCsv(rawColumns)
  const updateAssignments = columns.map((column) => `${column.trim()} = EXCLUDED.${column.trim()}`)
  for (const defaultColumn of ReplaceDefaultColumns.get(tableName) ?? []) {
    updateAssignments.push(`${quoteIdentifier(defaultColumn)} = DEFAULT`)
  }

  return `INSERT INTO ${quoteIdentifier(tableName)} (${rawColumns}) VALUES (${rawValues}) ON CONFLICT (${quoteColumns(conflictColumns)}) DO UPDATE SET ${updateAssignments.join(', ')}`
}

function rewriteMojangReplace(sql: string): string {
  if (!/^INSERT OR REPLACE INTO\s+"mojang"/i.test(sql)) return sql

  return `WITH deleted AS (
    DELETE FROM "mojang" WHERE "uuid" = @uuid OR "loweredName" = @loweredName
  )
  INSERT INTO "mojang" ("uuid", "username", "loweredName") VALUES (@uuid, @username, @loweredName)`
}

function rewriteTargetlessUpsert(sql: string): string {
  const match =
    /^INSERT INTO\s+"?([A-Za-z0-9_]+)"?\s*\(([^)]+)\)\s*VALUES\s*\(([^)]+)\)\s*ON CONFLICT DO UPDATE SET\s+(.+)$/i.exec(
      sql
    )
  if (match === null) return sql

  const [, tableName, rawColumns, rawValues, updateClause] = match
  const conflictColumns = TargetlessUpserts.get(tableName)
  if (conflictColumns === undefined) {
    throw new Error(`No ON CONFLICT mapping configured for table '${tableName}'`)
  }

  return `INSERT INTO ${quoteIdentifier(tableName)} (${rawColumns}) VALUES (${rawValues}) ON CONFLICT (${quoteColumns(conflictColumns)}) DO UPDATE SET ${updateClause}`
}

function bindParameters(sql: string, parameters: readonly unknown[]): { sql: string; parameters: unknown[] } {
  if (parameters.length === 1 && isPlainObject(parameters[0])) {
    const namedParameters = parameters[0]
    const indexes = new Map<string, number>()
    const values: unknown[] = []

    const rewrittenSql = sql.replaceAll(/[@:$]([A-Za-z_][A-Za-z0-9_]*)/g, (_match, name: string) => {
      let index = indexes.get(name)
      if (index === undefined) {
        index = values.length + 1
        indexes.set(name, index)
        values.push(namedParameters[name] ?? null)
      }

      return `$${index}`
    })

    return { sql: rewrittenSql, parameters: values }
  }

  let currentIndex = 0
  const rewrittenSql = sql.replaceAll('?', () => {
    currentIndex++
    return `$${currentIndex}`
  })

  return { sql: rewrittenSql, parameters: [...parameters] }
}

function splitCsv(value: string): string[] {
  return value.split(',').map((entry) => entry.trim())
}

function quoteColumns(columns: readonly string[]): string {
  return columns.map((column) => quoteIdentifier(column)).join(', ')
}

function quoteIdentifier(identifier: string): string {
  return `"${identifier.replaceAll('"', '""')}"`
}

function renderOrderBy(orderBy: readonly string[] | undefined): string {
  if (orderBy === undefined || orderBy.length === 0) return ''
  return ` ORDER BY ${quoteColumns(orderBy)}`
}
